- docs/ReviewProcess.md
Added more details to the API review overview:
1. Link to .NET API generation tool,
2. Link to example of API listing
3. Link to example of usage samples.
TODO: tools for other languages
TODO: example from some Azure SDK (Configuration Service)
TODO: examples and listings for other languages.
> Added links to tools, listing/sample examples

- docs/design/AzureSDKDesignGuidelines-java.md
Mostly centered around maven pom requirements.
> Java spec updates

- docs/design/dotnet/DesignGuidelines.md
Added what amounts to a TOC for the full Azure SDK .NET specific guidelines. 
I would be especially interested in feedback what else we should cover.
> TOC for .NET Design Guidelines

- docs/design/java/DesignGuidelines.md
This replaces my previous pull request, taking into account the additional feedback
> Updates based on feedback

- docs/design/python/DesignGuidelines.md
- docs/design/python/documented_module.py
- docs/design/python/documented_module_py3.py
> Python design guidelines/initial draft

- docs/ReviewProcess.md
Changes based in feedback from @wickste 
@bterlson, could you suggest text describing the format of JS listings (see TBD below)
@johanste , could you suggest text describing the format of Python listings (see TBD below)
> Updated API Review Process

- README.md
> Add link to our DevOps wiki

- docs/engineering-system/repo-structure.md
Outlines the guidelines on how to structure the repo.
> Add repo-structure document

- docs/design/Retry.mdk
- docs/design/dotnet/DesignGuidelines.mdk
- docs/design/dotnet/DotNetSpec.mdk
Small fixes based on feedback from @AlexGhiondea
> Small fixes based on feedback

- docs/design/dotnet/DesignGuidelines.mdk
The code was moved to the azure-sdk-for-net repo, so updating references.
> Update location of AzConfig

- docs/design/Errors.mdk
Uploading a new Errors.mdk for discussion in arch.board meeting.
> Changes to error/exception handling from JR

- docs/design/dotnet/DesignGuidelines.mdk
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/5503
> Add thread safety guidelines

- docs/design/java/DesignGuidelines.mdk
- docs/design/java/JavaSpec.mdk
Providing guidance around async and sync service clients, and other minor tweaks to fall into line with versioning discussion.
> Improving Java spec

- docs/design/python/DesignGuidelines.mdk
This mostly addresses the feedback that Bryan gave in GH-246.
> Update per review feedback from Bryan

- docs/design/DefaultPolicies.mdk
- docs/design/DesignGuidelines.mdk
This is the ordering from @JeffreyRichter
> Added default policies document

- docs/engineering-system/releases.md
This is definitely  not done and more meant to start to spark discussion. 
What requirements do we have to go to preview?
What requirements do we have to go to GA?
Outstanding things to think about:
+ Documentation requirements are not clear. @adrianhall is looking into this.
+ We don't have a clear understanding of how to test accessability of an API/code itself. @bterlson and I are looking into this
+ What prior art do we have on stress/perf test requirements? 
+ What common benchmarks are we using?
+ How do we integrate a supportability plan into this checklist?
What am I missing?
> Start of guidelines for preview and GA releases

- docs/design/Cancellations.mdk
- docs/design/Dependencies.mdk
- docs/design/OpenSource.mdk
- docs/design/README.md
- docs/design/Requirements.mdk
Updates for "SDK Component" to "Client library".  Also some generic changes to the language to ensure it is correctly spelled and proper grammar.
> Updated SDK Component to Client library and adjusted some grammar

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/adp_review.md
- .github/ISSUE_TEMPLATE/guidelines_change.md
* Added templates for issues related to design guidelines
* Added CODEOWNERS for all directories with the appropriate reviewers
* CODEOWNERS also provides review requirements
> Issue and PR requirements (templates)

- docs/design/DesignGuidelines.mdk
- docs/design/Documentation.mdk
Adding first crack at draft for doc guidelines.
@adrianhall
~~This is WIP, please do not review (nor merge) yet.~~ (now ready for review)
> General Guidelines: Documentation

- docs/design/DesignGuidelines.mdk
- docs/design/Proxy.mdk
> General Guidelines: Proxy Support

- docs/design/DesignGuidelines.mdk
- docs/design/DistributedTracing.mdk
> Added distributed tracing guidelines

- docs/design/ServiceNamespaces.mdk
This is a straw man for service groupings, to be used when a language has namespaces.
> General Guidelines: Namespaces

- docs/design/Async.mdk
- docs/design/DesignGuidelines.mdk
Codification of the discussed sync/async guidelines.
> Added sync/async guidelines

- docs/design/Configuration.mdk
- docs/design/EnvironmentVariables.mdk
- docs/design/typescript/DesignGuidelines.mdk
For discussion during today's meeting, and based on discussion from last time and further side conversations in the meantime.
> [General] Configuration guidelines

- docs/design/general/Definitions.mdk
- docs/design/general/DesignGuidelines.mdk
- docs/design/general/Terminology.mdk
This allows for easier addition of terms in language-specific guidelines.
> [General] split terminology and definitions

- docs/release-notes/preview/high-level-relnote-template.md
- docs/release-notes/preview/summary-preview1-java.md
- docs/release-notes/preview/summary-preview1-js.md
- docs/release-notes/preview/summary-preview1-net.md
- docs/release-notes/preview/summary-preview1-python.md
High level summaries for Preview 1 for Java, JavaScript, .NET.
and Python based on the template, high-level-relnote-template.md.
> Check-in of stubs of Preview 1 Summary Relnotes

- README.md
Added links to the table listing documentation links for each language
> Added documentation links in SDK overview

- docs/release-notes/preview/summary-preview1-java.md
* Add information and links to Event Hubs packages/readme.
@loarabia: I wasn't sure of the format you wanted for the Changelog items (ie. How to separate issues/features between each client library). 
Also, not sure where our preview documentation is at.
See: https://github.com/Azure/azure-sdk-for-java/pull/4244 for CHANGELOG.md PR.
> Update summary-preview1-java with EventHubs information

- docs/release-notes/preview/summary-preview1-js.md
This PR provides first draft for the Summary README for Javascript
> Summary readme for Javascript

- docs/design/typescript/APIShape.mdk
- docs/design/typescript/AzureCore.mdk
- docs/design/typescript/Configuration.mdk
- docs/design/typescript/Dependencies.mdk
- docs/design/typescript/DistributedTracing.mdk
- docs/design/typescript/Documentation.mdk
- docs/design/typescript/Errors.mdk
- docs/design/typescript/LRO.mdk
- docs/design/typescript/Logging.mdk
- docs/design/typescript/NPMPackage.mdk
- docs/design/typescript/Namespace.mdk
- docs/design/typescript/Pagination.mdk
- docs/design/typescript/PlatformSupport.mdk
- docs/design/typescript/Terminology.mdk
- docs/design/typescript/Testing.mdk
- docs/design/typescript/TypeScriptSpec.mdk
- docs/design/typescript/Versioning.mdk
Before: 262 issues, score = 64
After: 20 issues, score = 98
> Acrolinx run on TypeScript spec

- docs/engineering-system/codeowners-notifications.md
> add codeowners sync docs

- docs/README-TEMPLATE.md
- update contributing guide for template with the link to root contributing guide and other details - CLA, Code of Conduct etc.
@azure/azure-sdk-eng
> updated contributing guide for template

- _data/sidebars/releases_sidebar.yml
- _data/topnav.yml
- _layouts/post.html
- releases/2019-07-10/2019-07-10-dotnet-preview1.md
- releases/2019-07-10/2019-07-10-java-preview1.md
- releases/2019-07-10/2019-07-10-js-preview1.md
- releases/2019-07-10/2019-07-10-python-preview1.md
- releases/2019-07-10/index.md
- releases/2019-08-06/2019-08-06-dotnet-preview2.md
- releases/2019-08-06/2019-08-06-java-preview2.md
- releases/2019-08-06/2019-08-06-js-preview2.md
- releases/2019-08-06/2019-08-06-python-preview2.md
- releases/2019-08-06/index.md
Provides an updated Releases link in the top nav that points to a dedicated releases page
> Updates releases view

- README.md
The list is incomplete and many of the links are out of date. Removing in favor of documentation and details in each language repo that is referenced higher in this doc.
> Removing out of date table

- docs/tables/registered_namespaces.md
Added the following services to the registered namespace list:
* Azure Search
* Cognitive Services - Ink Recognizer
> Added Azure Search and Ink Recognizer namespaces

- docs/general/implementation.md
Logging examples for request, response and cancellation.
> (#484) Updated logging requirements.

- _data/sidebars/dotnet_sidebar.yml
Fixes to the .NET sidebar preview-2 API docs links
> Fixed preview-2 links

- docs/general/implementation.md
> Fix typos in Implementation | Depenendencies | Security section

- Gemfile.lock
- _data/sidebars/general_sidebar.yml
- _data/sidebars/golang_sidebar.yml
- _data/sidebars/home_sidebar.yml
- _data/topnav.yml
- docs/clang/approved_dependencies.md
- docs/golang/approved_dependencies.md
- docs/golang/design.md
- docs/golang/documentation.md
- docs/golang/implementation.md
- docs/golang/introduction.md
- docs/golang/refs.md
These are draft, so they just need to build so you can start editing, and ensure that nothing is actually "wrong" in the text.
> Golang guidelines DRAFT

- docs/java/design.md
More detail about module requirements and answering some questions about naming patterns. Please ask or propose more improvements in these two areas!
> Updated Java spec

- docs/policies/releases.md
after this discussion: https://github.com/Azure/azure-sdk-for-java/pull/5488#discussion_r335080374
> clarify interdependency in unified pipelines

- docs/dotnet/implementation.md
- docs/dotnet/introduction.md
Relates to Azure/azure-sdk-for-net#7675
> Add guidelines on enum-like structs for .NET

- docs/golang/design.md
- docs/golang/implementation.md
Added sections for logging, distributed tracing and versioning.
> Update design guidelines for Go

- docs/dotnet/introduction.md
Not 100% sure this is where you want this point, but the current link 404s, and this is the closest I could find.
> Fix example README target (.NET docs)

- docs/policies/repostructure.md
cc @Azure/azure-sdk-eng 
PTAL @danieljurek @KrzysztofCwalina
> Update repo structure doc to include other paths beyond sdk folder.

- docs/policies/releases.md
@kurtzeborn @mikeharder 
cc @Azure/azure-sdk-eng
> Update daily dev package versioning

- docs/golang/design.md
- docs/golang/documentation.md
- docs/golang/introduction.md
Consolidated duplicate client sections.
Added details for model types.
Type-o and rewording.
> Go clean-up

- docs/dotnet/implementation.md
> Must not use MUST-NOT

- docs/java/design.md
* remove httpLogDetailLevel and add new API
* Interfaces should not start with 'I'
* Maven artifact IDs must follow similar naming structure and include group in name
> Slight Java spec updates

- docs/clang/design.md
Apply the naming fixes brought up in the Nov 1st meeting.
> Fix design guidelines

- docs/policies/releases.md
Per our recent meeting about idiomatic versioning for JS packages in npm, this PR attempts to clarify the JS section with specific language and examples around how we expect to manage package versions.
All feedback is welcome, please feel free to help me wordsmith things better.
> Update section on JS/TS versioning

- README.md
- Fixed android link
- Removed android and iOS doc links for now, they were 404ing
> Readme updates to fix links

- docs/clang/design.md
We discussed this change in the meeting on friday the 18th.
Please comment if the naming doesn't seem quite right.
> change guidelines on internal structs

- docs/clang/design.md
Change az_error in the object model to az_result.
> Object model fixes

- docs/clang/implementation.md
see #686 for details.
Please do not merge until signoff by IOT and azure-c-sdk teams.
> variable initialization revision

- README.md
Added links to C99 guidelines and the c99 repository to README.md
> add c99 guidelines to readme.md

- releases/2019-12/2019-12-dotnet.md
- releases/2019-12/2019-12-java.md
* Updates 2019-12-java.md for Event Hubs.
* Fixes typo in .NET release file.
> Update 2019-12-java.md for Event Hubs

- _data/releases/latest/java-packages.csv
- releases/2019-12/2019-12-java.md
* Update versions for Event Hubs.
* Remove non-critical callouts.
> Update versions for Event Hubs.

- releases/2019-09-17/index.md
- releases/2019-10-11/index.md
- releases/2019-11/index.md
- releases/2019-12/index.md
- releases/latest/index.md
PTAL @bterlson @xirzec @ramya-rao-a
> For consumers we should call it JavaScript not TypeScript

- releases/latest/index.md
> Add all package indexes to latest releases index page

- docs/policies/releases.md
Update message in changelog guidance
> Update Changelog Guidance

- docs/dotnet/introduction.md
PTAL @Petermarcu @KrzysztofCwalina
> Add note about symbol publishing

- docs/typescript/design.md
Fixes up #534. This is just documenting current practice (minus some inconsistencies which should hopefully not happen again 😁)
> [JS/TS] Add some retry guidelines

- releases/2019-12/2019-12-js.md
- releases/2020-01/2020-01-js.md
This PR adds the January release notes for JS libraries
> Jan release notes for JS

- _data/releases/latest/js-packages.csv
- releases/2020-01/2020-01-js.md
Add the 1.0.0-preview.1 release of the Track 2 Text Analytics package and fix up the release notes to have the right package name.
> Add text analytics package

- _data/releases/latest/java-packages.csv
- releases/2020-01/java.md
- Include text analytics in release notes
- Direct tracing package to opentelemetry and not opencensus
> Release notes update for Text Analytics

- releases/2020-01/dotnet.md
Update of release notes to include Event Hubs.
> January Release Notes: Addition of Event Hubs information

- _data/releases/latest/js-packages.csv
- releases/2020-01/js.md
- add storage change logs
- add storage-file-datalake library
> Update js 2020-01 release notes

- releases/2020-01/js.md
This PR adds some noteworthy call outs for Text Analytics and Event Hubs
> [JS] Updates to the Jan release notes

- docs/java/design.md
Copy / paste from general guidelines the 'Conditional requests' section.
Fixes #706
> Update Java guidelines with 'Conditional requests' text

- docs/policies/releases.md
> Add CHANGELOG guidance to link fixed issues

- _includes/tables/environment_variables.md
- docs/general/azurecore.md
- docs/general/design.md
This reverts commit 6e497b1f19a70b39a101c04dbef6744a9a6c4f50.
Related #1049
> Revert "(#663) sovereign cloud support (#987)"

- docs/dotnet/introduction.md
- Updated guideline for LRO (mainly around rehydrating an existing LRO).
- Updated async collection guidelines per renames in Azure.Core
> Updates to LRO and Async Collection Guidelines

- docs/dotnet/introduction.md
Based on PR feedback, add requirement about overloading ModelFactory methods.
> Add requirement for model factories in .NET

- releases/2020-03/java.md
Update TA CHANGELOG for March 2020
> Update TA CHANGELOG for March 2020

- docs/dotnet/introduction.md
Updated .NET Guidelines with:
1. New guidelines for using collections in models
2. New guidelines for parameter "bags"
3. Clarified model namespace and sync methods guidelines
4. Reacted to API changes/renames in Azure.Core  
5. Updated stale links
> Mics updates to the .NET Design Guidelines

- releases/2020-03/java.md
Add App config minor version changelog and version bump up
> App config minor version changelog and version bump up

- releases/2020-03/java.md
Contains high level release note for the March 2020 release for Java.
> Java March 2020 Release

- releases/latest/all/dotnet.md
- releases/latest/all/java.md
- releases/latest/all/js.md
- releases/latest/all/python.md
- releases/latest/dotnet.md
- releases/latest/index.md
- releases/latest/java.md
- releases/latest/js.md
- releases/latest/python.md
> Update New/All links in package index

- docs/cpp/implementation.md
Seed initial platform list based off .NET 5's supported platforms
> Update Platform List

- eng/ci.yml
- eng/githubio-linkcheck.yml
- eng/scripts/Verify-Links.ps1
- eng/scripts/ignore-links.txt
linkchecker has been having some issues so switching back
to Verify-Links script with some new features and optimizations.
> Switch back to Verify-Links script

- releases/2020-04/java.md
- updated AppConfig and Text Analytics release note
> Updated AppConfig and Text Analytics release note

- css/customstyles.css
The preview badges were changing to blue on hover. This update will change it to lighter grey on hover
> Adjust badge hover colors

- docs/cpp/design.md
- docs/cpp/implementation.md
…as the GCC on RHEL does not support this feature.
> [cpp] Remove nested namespace declarations

- docs/java/refs.md
> Update link to parent pom

- docs/dotnet/introduction.md
> Update sample guidelines for .NET

- docs/policies/reviewprocess.md
Per discussions with @Petermarcu - updated policy for what constitutes "sign-off" in the meeting and meeting attendee requirements.
> Added new policy for meetings

- releases/2020-04/python.md
> Release notes for python form recognizer

- docs/python/implementation.md
Variable `resource` was not defined.
> Fix variable name in Python doc

- _includes/js-allpackages.html
- eng/scripts/Verify-Links.ps1
Fix broken links not discovered until after fix.
> Fix link checker to allow spaces

- _data/releases/latest/dotnet-packages.csv
- releases/2020-04/dotnet.md
Release notes for the .NET Azure.AI.FormRecognizer 1.0.0-preview1 library.
> Release notes (.NET): Azure.AI.FormRecognizer 1.0.0-preview1

- _data/releases/latest/java-packages.csv
- releases/2020-04/java.md
Release notes for the Java `azure-ai-formrecognizer` 1.0.0-beta.1 library.
> Release notes Java Form Recognizer 1.0.0-beta.1

- docs/policies/reviewprocess.md
- Reviewing samples was suggested over email.
- Pavel opened an issue to track using an issue for minor reviews rather than email.
> Review samples and use github issues

- _data/releases/latest/js-packages.csv
- _data/releases/latest/python-packages.csv
The other two languages have already been updated
> Adding form recognizer to that latest releases

- _data/allpackages/java-packages.csv
Since Service Bus is still in preview, change "Replaces" with "Will be replaced by"
> Update note on SB for Java all releases csv

- _config.yml
- _includes/app_insights.html
- _layouts/default.html
- _layouts/redirect.html
* New include - app_insights.html - which provides the JS Snippet for App Insights monitoring
* Updated default.html layout to include app_insights if configured
* Added App Insights monitoring for redirects as well.
All that is required is to place the App Insights instrumentation key within the `_config.yml` file to enable App Insights monitoring.
> Added App Insights monitoring (without configuration)

- releases/2020-05/python.md
storage was split by event hubs
> Updating the release notes

- releases/2020-05/java.md
Updating java.md to include release notes for May release.
> Release notes for Event Hubs - May 2020

- docs/typescript/design.md
Realized this was never pinned down, so doing so now. We'll be joining our python bretheren.
> [TS] We use begin for lro

- eng/scripts/Update-Release-Versions.ps1
@scbedd please take a look. I didn't find any delta between the tags and the version info in the blob storage so I stopped using tags and started pulling the blob data.
> Update script to get version from docs instead of tags

- docs/ios/design.md
- docs/ios/introduction.md
Part 1 is mostly done, but needs reviewed. We'll continue to iterate as we have our guidelines discussion meetings.
Changes are made in parallel to the SDK to align with these guidelines updates in Azure/azure-sdk-for-ios#306
> iOS guidelines update

- releases/2020-06/python.md
Saw @ShivangiReja's comment on this PR: https://github.com/Azure/azure-sdk/pull/1370
> [text analytics] link to b6 changelog specifically

- _posts/2020-05-26-async-iterators.md
I'll continue to noodle on this (generally cleaning things up, adding more realistic samples, and trimming content where I can), but getting this out there for feedback!
> Add async iterator blog

- releases/2020-06/dotnet.md
* Added a new format for each library.
* Updated all the libraries in alphabetical order.
> Format .NET release notes for June release

- releases/2020-06/java.md
Add Java Form recognizer release notes
> Add Java Form recognizer June release notes

- releases/2020-06/dotnet.md
Following new guidance for release notes:
https://azure.github.io/azure-sdk/policies_releasenotes.html#whats-a-developer-impacting-change
> Add June .NET FR info

- _data/releases/latest/java-packages.csv
Adds Azure Core packages and Storage Common to the `releases/latest` tracker.
> Add Missing Java Pacakages in releases/latest

- _posts/2020-05-19-formrecognizer.md
Update Form recognizer blog post for reflecting preview/beta 3 changes for the client library.
> Update Form Recognizer blog for beta 3

- docs/java/spring.md
Fixes #1444 
Because it is a minor wording change I am going to immediately go ahead and merge without additional review.
> Using better phrasing in the Java Spring guidelines.

- docs/ios/implementation.md
Fixes: https://github.com/Azure/azure-sdk/issues/1440
> Replace whitelist term for AllowList in ios documentation

- docs/clang/implementation.md
@JeffreyRichter another update similar to your other one.
> Update white list to allow list

- _data/allpackages/dotnet-packages.csv
- _data/allpackages/java-packages.csv
- _data/allpackages/js-packages.csv
- _data/allpackages/python-packages.csv
- _data/releases/latest/dotnet-packages.csv
- _data/releases/latest/java-packages.csv
- _data/releases/latest/js-packages.csv
- _data/releases/latest/python-packages.csv
- _includes/releases/all/pkgrow.md
- _includes/releases/all/pkgtable.md
- _includes/releases/pkgrow.md
- _includes/releases/pkgtable.md
- eng/scripts/Generate-Package-Index.ps1
- eng/scripts/Query-Azure-Packages.ps1
- eng/scripts/Update-Release-Versions.ps1
> Rename Service column to DisplayName

- docs/policies/repostructure.md
This PR adds a section to the repo structure guidance that deals with the question of application frameworks.
> App framework module placement guidance

- releases/2020-06/java.md
* Updated azure cosmos GA changelog and release notes to June release
> Updated azure cosmos GA changelog and release notes to June release

- releases/2020-07/java.md
* Added cosmos july release notes
> Added cosmos july release notes

- docs/policies/releases.md
Finishes addressing https://github.com/Azure/azure-sdk-tools/issues/642
> Update release policy to incorporate mono-releases

- releases/2020-07/python.md
Add changelog and installation notes as the title says.
Note: @xiangyan99  I intentionally did not include minor bugfixes, shout if this meets the threshold for the core release notes or if anything else should be adjusted.
> Add Python Service Bus 7.0.0b4 (Track 2, preview 4, July) release notes.

- releases/2020-07/python.md
azure-eventhub 5.2.0b1 release notes update
> python eventhubs release notes for July

- releases/2020-07/java.md
Add Service Bus to July release notes.
> Add Service Bus to July release notes.

- releases/2020-08/java.md
Added cosmos August release notes
> Update cosmos august release note

- releases/2020-07/java.md
Adding notes for the stable release for now, as beta was having issues and is not complete.
> Updated Java README for the KeyVault stable July 2020 release.

- eng/pipelines/version-updater.yml
- eng/scripts/Generate-Package-Index.ps1
> Add dotnet docs package index sync

- docs/ios/design.md
- docs/ios/introduction.md
Getting closer to being ready for review
> iOS guidelines updates

- releases/2020-08/java.md
* Updated release docs for azure-cosmos release 4.3.0
> Updated release docs for azure-cosmos release 4.3.0

- js/customscripts.js
> only search first column

- docs/ios/design.md
Updates guidelines on cancellation based on updated implementation in AzureCore.
> CancellationToken updates

- .github/CODEOWNERS
Adding myself as a release code owner since I'll be managing the .NET release process from now on.
> Added kinelski as a code owner for releases

- releases/2020-08/python.md
Truth in advertising.
As always @xiangyan99 shout if I've been too granular with my release note entries, this was a large delta.
>  Add Python Service Bus 7.0.0b5 (Track 2, preview 5, August) release notes.

- releases/2020-08/dotnet.md
Release notes for .NET 2020-08 Form Recognizer.
> [FormRecognizer] Updated .NET 2020-08 release notes

- releases/2020-08/java.md
> Add Java App Configuration release notes

- docs/policies/releases.md
> Add note about GA release notes

- releases/2020-08/python.md
Adding information about Azure Cosmos DB Python SDK
> Azure Cosmos DB Python SDK

- releases/2020-08/js.md
~This is a draft. We will be actively updating this.~
Not a draft anymore 🌞 feedback appreciated.
> [JS] August release notes

- releases/2020-08/dotnet.md
- releases/2020-08/java.md
- releases/2020-08/python.md
> Adding storage updates

- releases/2020-09/dotnet.md
Including FormRecognizer 3.0.0 out-of-band release.
> [.NET] Added FormRecognizer 3.0.0 to 2020/09 release notes

- releases/2020-09/index.md
- releases/2020-09/java.md
Update release notes for Java FR GA
> Update release notes for Java Form Recognizer GA

- docs/golang/design.md
delete duplicate word, from "policy policy" to "policy".
> delete duplicated word

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitattributes
- .vscode/extensions.json
- .vscode/tasks.json
- CONTRIBUTING.md
- _config.yml
* Make sure line endings are handled right whether in a container or WSL
* Performance improvements to building Docker container
* Added recommended extensions for using devcontainer and following Microsoft docs guidelines
> Improvements to the devcontainer

- _data/releases/latest/java-packages.csv
Fixes the ALL CAPS for Anomaly detector here - https://azure.github.io/azure-sdk-for-java/anomalydetector.html
> Add Anomaly detector to Java packages

- releases/2020-09/dotnet.md
- releases/2020-09/java.md
* Add Event Hubs and Service Bus release notes.
> Add Event Hubs and Service Bus release notes.

- releases/2020-09/java.md
* Updated release notes for azure-cosmos 4.4.0
> Updated release notes for azure-cosmos 4.4.0

- releases/2020-09/java.md
add release notes for azure spring cloud September release
> add release notes for spring cloud

- releases/2020-09/java.md
* Added azure-cosmos 4.4.0.beta.1 release notes
> Added azure-cosmos 4.4.0.beta.1 release notes

- releases/2020-09/java.md
add release note for azure spring boot 2.3.5
> add release noate for azure spring boot 2.3.5

- releases/2020-09/js.md
This PR has changes based on the last set of feedback that was provided to #1750
cc @sadasant, @jongio
> Updates to JS Release notes based on last set of review comments

- releases/2020-09/dotnet.md
> [.NET] Update 2020-09 release notes with missing packages

- eng/scripts/release-template/c.md
- eng/scripts/release-template/cpp.md
- eng/scripts/release-template/index.md
Add templates for C and C++ releases
> Release templates for Embedded C and C++

- _data/releases/latest/c-packages.csv
- _data/releases/latest/cpp-packages.csv
- _data/sidebars/releases_sidebar.yml
- _includes/releases/c.md
- _includes/releases/cpp.md
- _includes/releases/nav.md
- _includes/releases/variables/c.md
- _includes/releases/variables/cpp.md
- eng/scripts/Update-Release-Versions.ps1
- eng/scripts/release-template/index.md
- releases/latest/c.md
- releases/latest/cpp.md
- releases/latest/index.md
This should add the basic c and c++ package indexes:
Index package:
C page
C++ page
> Add C and C++ package indexes

- releases/2020-09/java.md
[Out of Bound] 
TA release a preview version in 09/17/2020
This is an out of bound release.
> Text Analytics September Release note, OutOfBand

- releases/2020-09/dotnet.md
TA 5.1.0-beta.1 was released last week, so adding it to the release notes.
Also, I moved `Identity` section with the rest
> Add info for TA and modify .NET release file

- docs/cpp/design.md
- docs/cpp/implementation.md
- docs/tables/registered_namespaces.md
Cleanup todos surrounding Azure::Core
Add links to the clang-formating file
> Cpp design docs

- docs/cpp/design.md
This depends on https://github.com/Azure/azure-sdk-for-cpp/pull/197/
> [cpp] Add 'extensible enum' guidelines

- eng/scripts/Generate-Package-Index.ps1
Fixes https://github.com/Azure/azure-sdk/issues/1867
> Make doc MD table links relative to docs.microsoft.com

- _data/releases/latest/c-packages.csv
> Change Iot to IoT

- _data/releases/latest/java-packages.csv
- _data/releases/latest/js-packages.csv
- _data/releases/latest/python-packages.csv
This PR adds metrics advisor to package index for Java, JS and python.
.NET is still waiting to release.
> Add metrics advisor new package to package index

- docs/golang/approved_dependencies.md
- docs/golang/design.md
Added new dependency.
Updated section on optional method parameters.
Fixed up comments for pollers.
Some other minor tweaks.
> Updates to Go design guidelines

- releases/2020-10/index.md
- releases/2020-10/java.md
October release notes for Java.
> Java October 2020 release notes

- releases/2020-08/java.md
- releases/2020-09/java.md
- releases/2020-10/java.md
- Add release version notes for Azure Spring Boot
> Add release version notes for Azure Spring Boot

- docs/policies/repobranching.md
> Add note about immutable release tags

- _includes/refs.md
- releases/2020-09/cpp.md
- releases/2020-10/cpp.md
> update c and cpp links from refs

- _data/sidebars/dotnet_sidebar.yml
- _data/sidebars/java_sidebar.yml
- _data/sidebars/js_sidebar.yml
- _data/sidebars/python_sidebar.yml
- docs/policies/README-EXAMPLE.md
- docs/policies/README-TEMPLATE.md
- releases/2020-10/java.md
Fixed the broken links from https://github.com/Azure/azure-sdk/pull/1990
> Fixed the broken links from report

- _data/releases/latest/c-packages.csv
> Update latest preview versions

- _data/releases/latest/dotnet-packages.csv
Its a package with just a couple abstractions that Storage uses to share some keyvault concepts between storage libraries
It now in Azure.Core in track 2
> Change KV pkg to storage.

- releases/2020-11/dotnet.md
Also fixes CHANGELOG links to follow recommended pattern for existing packages.
> Add Key Vault release information

- _includes/releases/nav.md
- _includes/releases/pkgrow.md
- _includes/releases/pkgtable.md
- css/customstyles.css
fixes: https://github.com/Azure/azure-sdk/issues/2036
fixes: https://github.com/Azure/azure-sdk/issues/2024
Applying wrap to table style to avoid right grow.
Will keep the table growing down like:
> Make table to wrap words from all content by words

- eng/pipelines/version-updater.yml
- eng/scripts/Update-DevOps-WorkItems.ps1
This script is intended to update our associated devops
work-items with any new shipping information or updates to
the package index csv files.
> Initial commit of devops work-item update script

- releases/2020-11/dotnet.md
It includes release notes for TA and FR
> .NET Form Recognizer release notes

- releases/2020-11/java.md
This PR adds release notes Java November month releases excluding the Service Bus GA updates.
> Java November release notes

- docs/android/approved_dependencies.md
- docs/android/design.md
- docs/android/documentation.md
- docs/android/implementation.md
- docs/android/introduction.md
So far I made changes based on the Android Arch discussion on September 9th, 2020. Will keep adding changes as they are discussed.
> Android Guidelines Revision for First Preview

- releases/2020-11/js.md
This PR contains some maintenance changes (reordering lines) and changes the Service Bus highlights to better reflect the changes that have been introduced since our GA release.
> [November JS] Updated the Service Bus highlights since we've released a GA

- releases/2020-11/js.md
This adds release notes for text analytics November beta release.
> [Text Analytics] Add release notes for November

- _data/sidebars/general_sidebar.yml
- docs/policies/releases.md
- Cleaning up the policies section.
- Separating Repo related topics from process topic
- Adding Release exit criteria section
You can find a live demo of these changes here specifically under the release section here:
https://salameer.github.io/azure-sdk/policies_releases.html
> Adding release exit criteria and Cleaning up polocies

- releases/2020-11/java.md
Add Service bus changes to release notes after SB GA.
> Service Bus GA release updates Java

- docs/dotnet/implementation.md
- docs/dotnet/introduction.md
> Updates to out of date guidelines #2086

- docs/cpp/design.md
Update the extensible enum example.
> Fix extensible enum example

- _data/releases/latest/js-packages.csv
- docs/python/design.md
- eng/ignore-links.txt
> add twitter link to ignore list. standard GET are being rejected

- docs/cpp/introduction.md
Update the guidelines to remove the c_ prefix
> Update guidelines for constants

- releases/2020-12/java.md
Update release note for December release of Azure Spring Boot and Azure Spring Cloud
> update release notes for Spring December release

- _data/releases/latest/cpp-packages.csv
Live demo:
https://vhvb1989.github.io/azure-sdk/releases/latest/index.html#c
> Adding C++ identity to latest release info

- _includes/tables/environment_variables.md
This PR adds the `ALL_PROXY` environment variable to the variable table.
> Add ALL_PROXY environment variable

- releases/2020-12/index.md
> adding missing permlink for sidebar

- releases/2021-01/index.md
Please review, edit, merge or cancel at your will 👍
> General highlights, at least from the JS perspective

- _data/releases/latest/go-packages.csv
- _data/sidebars/releases_sidebar.yml
- _includes/refs.md
- _includes/releases/go.md
- _includes/releases/languages.md
- _includes/releases/nav.md
- _includes/releases/variables/go.md
- docs/policies/releases.md
- eng/scripts/Update-Release-Versions.ps1
- eng/scripts/release-template/go.md
- eng/scripts/release-template/index.md
- releases/latest/go.md
Adding release notes templates and package indexes for Go.
> Adding release notes templates and package indexes for Go

- releases/2021-01/java.md
Update  Service Bus detail for January 2021 release.
V 7.0.1
> Update release notes - service bus changes for January 2021

- docs/golang/design.md
Clients and their receivers, along with response envelopes are passed by value.
> update Go to include recent changes

- docs/cpp/implementation.md
- docs/cpp/introduction.md
Cleanup of C++ guidelines
Additional cleanups are coming, please keep comments focused only to the lines of code changing in the PR.
> C++ Guidelines cleanup

- releases/2021-01/java.md
Update release notes for spring modules.
> Update release notes for spring modules.

- docs/dotnet/introduction.md
- Added a section about hierarchical resources.
> Guideline updates #3

- _data/sidebars/general_sidebar.yml
- docs/ios/design.md
- docs/ios/implementation.md
This PR will eventually cover all of the changes needed for the MQ initiative around guidelines restructuring.
> iOS guidelines re-organization

- docs/golang/design.md
Updated synchronous section with more details.
> Add section on cancellation to Go

- releases/2021-02/dotnet.md
The focus of these changes is to add the February release notes for the Event Hubs client libraries.
> [February Release Notes] Event Hubs

- docs/dotnet/introduction.md
Small cleanup to finish .net gap project.
> last batch of .NET guideline gap cleanup

- releases/2021-02/java.md
- Add release entries for Azure Core AMQP and Azure Event Hubs
> Add release entries for Azure Core AMQP and Azure Event Hubs

- docs/policies/README-TEMPLATE.md
- docs/policies/migration-guide-template.md
- docs/policies/releases.md
> Fix branding for frameworks

- eng/pipelines/generate-releasenotes.yml
- eng/scripts/Generate-Release-Structure.ps1
- eng/scripts/Generate-ReleaseNotes.ps1
Ensure release-template files have been copied over before generating release notes.
> Add generation of release structure to release notes generation

- releases/2021-03/js.md
> Identity highlights for the March releases

- releases/2021-03/java.md
- Fixup missing Groupid.
- Fixup spacing.
> Fixup missing groupId

- releases/2021-03/ios.md
> [Communication] Update iOS March release

- releases/2021-02/java.md
update release notes for Spring February OOB release
> 210309 spring oobrelease gzh

- releases/2021-03/dotnet.md
@tophpalmer , @ankitarorabit , @RezaJooyandeh please take a look to the .Net release notes.
> Update ACS GA .Net Releases

- releases/2021-03/java.md
This PR is to update March release notes for Azure Spring:
- Added installation instructions for Azure Spring users.
- Added release highlights for Azure Spring modules.
> Update release notes for Azure Spring March release

- releases/2020-11/python.md
FYI @jbeauregardb fixing broken link caused by https://github.com/Azure/azure-sdk-for-python/pull/17668.
> Fix broken link

- docs/policies/support.md
Updating support.md per feedback from CELA
> Updates per CELA feedback

- _data/releases/latest/python-packages.csv
Trying to get my docs published to github.io
> Update for document translation

- releases/2021-04/dotnet.md
The focus of these changes is to revise the release notes for Event Hubs.
Also included is a normalization of package additions.
> [April Release Notes] Event Hubs content

- releases/2021-04/ios.md
Release notes for iOS 1.0.0-beta.11
> Beta.11 Release Notes

- releases/2021-03/dotnet.md
@czubair please check this PR, ACS remove the release notes from March
> Remove ACS GA release notes to April

- releases/2021-04/dotnet.md
instead of package name for consistency with other packages
> Update dotnet.md to use translation document

- _includes/tables/data_namespaces.md
- docs/java/introduction.md
This PR updates guidelines for creating new exceptions and throwing non-public exception types.
> Update exception guidelines and add new approved group names

- releases/2021-04/java.md
This PR is to update April release notes for Azure Spring:
- Added installation instructions for Azure Spring users.
- Added release highlights for Azure Spring modules.
> Update release notes for Azure Spring April release

- eng/scripts/Generate-ReleaseNotes.ps1
- Add bracket around `[DateTime]$releasePeriod`
> Fix evaluate [DateTime] before assign it to FromDate

- docs/policies/releasenotes.md
- Updated to doc based on updated workflow.
> Update Producing Release Notes Docs

- releases/2021-04/js.md
- Updating April Release notes for JS for sdks that were left out
> april js release notes remaining sdks

- releases/2021-05/android.md
- releases/2021-05/index.md
- releases/2021-05/ios.md
Also updated the Release Highlights.
> Mobile release notes for May 2021

- releases/2021-05/index.md
- Update release highlights for Azure Web Pubsub service
> Update release highlights JS

- eng/pipelines/template/steps/generate-releasenotes.yml
- eng/pipelines/version-updater.yml
- eng/scripts/Generate-ReleaseNotes.ps1
- eng/scripts/Update-Release-Versions.ps1
- Merging Pipelines
- Add only packages that were recently updated.
> Merge pipelines generate-releasenotes.yml into version-updater.yml

- eng/pipelines/template/steps/generate-releasenotes.yml
Fix bugs related to resetting git branch between steps.
> Fix bug in generation of release notes

- eng/pipelines/template/steps/generate-releasenotes.yml
- Add step for cleaning up stale branches.
> Add step for deleting stale branches

- eng/pipelines/template/steps/generate-releasenotes.yml
- Fix parameters in Branch cleanup step
> Update Branch cleanup step parameters

- eng/scripts/Generate-ReleaseNotes.ps1
- Fix bug in eng\scripts\Generate-ReleaseNotes.ps1
> Fix bug in eng\scripts\Generate-ReleaseNotes.ps1

- eng/scripts/PackageList-Helpers.ps1
- eng/scripts/Query-Azure-Packages.ps1
- eng/scripts/Update-Release-Versions.ps1
- Only update versions for new packages in Update-Release-Versions
- Use link cache when checking lines in Update-Release-Versions
- Skip links that we don't need to validate
- Use hashtables when updating package in Query-Azure-Packages
> Ensure all new packages are updated in Update-Release-Versions

- eng/scripts/release-template/ios.md
Follow up to https://github.com/Azure/azure-sdk/pull/2984
> Update iOS release notes template.

- _data/releases/2021-05/js.yml
- _data/releases/2021-06/js.yml
- releases/2021-06/index.md
Moving notes from here - https://github.com/Azure/azure-sdk/pull/2891
> JS release notes and highlights

- releases/2021-06/index.md
- All GAs or first beta of JS package has been included in the release highlights.
> update with remaining JS highlights

- _includes/releases/go.md
> Fix go package filtering

- eng/scripts/Generate-ReleaseNotes.ps1
- Add logic for adding content of changelog sections into the release notes.
- This resolves issue https://github.com/azure/azure-sdk/issues/2539
> Add logic to collect changelog sections in the release notes

- _data/releases/latest/java-packages.csv
- releases/2021-01/java.md
it is a track 2 package
This PR quickly unblocks Azure/azure-sdk-for-java#22469
> azure-verticals-agrifood-farming has dependencies on azure-core.

- _data/releases/latest/python-packages.csv
@chidozieononiwu this should fix the warnings in release note gathering at https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1032554&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d2958828-97d6-5036-8b4a-07a267845bb6&l=14
> Update repopath for azure-mgmt-redis

- docs/general/documentation.md
> Remove duplicated 'the'

- _includes/google_analytics.html
> Fix Missing GA Tag

- eng/scripts/Query-Azure-Packages.ps1
> Add auto add cpp packages based on tags

- docs/python/implementation.md
`interchangable` to `interchangeable`
I am sorry that I did not make a new branch in order to open a pull request on previous PR.
> Fix typo in python/implementation.md

- _data/releases/latest/dotnet-packages.csv
Fixes https://github.com/Azure/azure-sdk/issues/2016
> Unhide Microsoft.Extensions.Azure

- _data/releases/latest/c-packages.csv
Closes https://github.com/Azure/azure-sdk-for-c/issues/2002.
> Unhide EmbeddedC Storage library docs

- docs/dotnet/introduction.md
Fixes https://github.com/Azure/azure-sdk/issues/3745
> Add Azure.Monitor namespace to approved list in .NET design guidelines

- _data/releases/latest/python-packages.csv
@weshaggard -- I think this track 2 package is not marked correctly in the metadata which prevents it from being onboarded to docs.ms.
> Mark azure-mgmt-servicelinker as New

- _includes/releases/header.md
changing "support retired" to "retired" for clarity
> changing "support retired" to "retired"

- _data/releases/latest/python-packages.csv
Reclassify the service as Monitor, set package to retired, specify replacement package and migration guide
> Update Python azure-loganalytics row in CSV

- _data/releases/latest/python-packages.csv
Latest published version is 1.0.0b2
> Use latest published version for azure-communication-networktraversal

- _data/releases/latest/java-packages.csv
- Add Resource Manager Security Insights
> Add ResourceManager Security Insights

- _data/releases/2021-11/js.yml
- fix broken link due to file rename.
> fix broken TROUBLESHOOTING.md link

- _data/releases/latest/python-packages.csv
@weshaggard Could I point to the main branch instead of a specific version? or the doc generation can't work without a specific version.
The main branch is: https://github.com/Azure/azure-uamqp-python/tree/master
> Update uamqp branch info

- Gemfile.lock
- Fixes issues flagged by component governance.
> Fix issues flagged by component governance

- css/customstyles.css
- Fixes in part https://github.com/Azure/azure-sdk/issues/4188
- Make selected section highlighted.
> Fix Highlighted Section Issue

- _data/releases/latest/python-packages.csv
This service client was never implemented.
> (chore): remove the dps provisioning service client

- docs/typescript/design.md
I attempted to explain the problem clearly, but I feel like the language can be cleaned up a bit. Suggestions are welcome.
> [js] Add guidance about avoiding subclassing across package boundaries.

- Gemfile.lock
Fix Component Governance Issues
> Update dependency flagged by Component Governance

- .github/CODEOWNERS
The focus of these changes is to update the "Team Management" section to capture current responsibilities.
> [CODEOWNERS] Update leads + languages

- docs/tracing/distributed-tracing-conventions.yml
Adopt [requirement levels](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md)
> Tracing schema: update requirement levels

- releases/2022-05/c.md
- releases/2022-06/c.md
cc @czubair, @vhvb1989, @antkmsft
> Update latest embedded c release notes for May and June (no release)

- .github/CODEOWNERS
Taking over from Deya starting from July.
> [CODEOWNERS] Add Timo as JS release driver

- Gemfile.lock
- Fix issues flagged by Component Governance
> Update nokogiri to >=1.13.6

- _data/sidebars/general_sidebar.yml
Can't help myself. This always catches my eye. :)
> Github -> GitHub

- docs/policies/support.md
Resolve https://github.com/Azure/azure-sdk-tools/issues/3715
Tracking issue: https://github.com/actions/virtual-environments/issues/5583
> Bump macOs version to macos-11

- _data/releases/latest/python-packages.csv
@danieljurek @annatisch @sima-zhu
> Update `azure-ai-ml` assignation to `Machine Learning` service

- _data/releases/latest/python-packages.csv
See title. @annatisch I think I have it this time >.<
> Update `azure-ai-ml` such that it appears in docs.ms ToC under `Machine Learning` service

- docs/ios/design.md
Updates guidance on enums to use the "unbreakable" extensible enum.
> iOS - Update Enum Guidelines

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/adp_api_review_and_signoff.md
- .github/ISSUE_TEMPLATE/adp_review_service_intro.md
- .github/ISSUE_TEMPLATE/guidelines_change.md
Added myself to the Architecture section of the CODEOWNERS file and as an assignee on the architecture board review scheduling issue templates.
> Ronniegeraghty arch board updates

- docs/dotnet/implementation.md
I want to codify the agreement we had made back in the day here https://github.com/Azure/autorest.csharp/issues/1771.
> initial draft on param ordering guidelines

- _data/releases/latest/dotnet-packages.csv
Use a friendly name instead of the package name
> Update display name for Identity Brokered Auth package

- _data/releases/latest/java-packages.csv
Update Call display name to align with other communication modules
Updating to be in same service name as Communication
> Updating Call Automation entry (java)

- _data/releases/latest/python-packages.csv
RE: VM Health SDK deprecation
https://github.com/Azure/sdk-release-request/issues/3456
> [work load monitor] deprecate

- _data/releases/latest/python-packages.csv
https://azure.github.io/azure-sdk/releases/deprecated/index.html#python
> [workloadmonitor] show deprecated in github.io

- docs/dotnet/introduction.md
Update the LRO documentation to reflect polling the operation rather than the client.
Contributes to #3678
> Update LRO Documentation

- releases/2022-09/c.md
- releases/2022-10/c.md
- releases/2022-12/c.md
Similar change to https://github.com/Azure/azure-sdk/pull/4410
> Update latest embedded c release notes for Sept, Oct, and Dec (no release)

- _data/releases/latest/dotnet-packages.csv
Change "EventGrid" to "Event Grid"
> Fix invalid service name

- _data/releases/latest/dotnet-packages.csv
- _data/releases/latest/java-packages.csv
- _data/releases/latest/js-packages.csv
- _data/releases/latest/python-packages.csv
Add 'azure-load-testing' to MSServiceDoc
Linked PR: https://github.com/Azure/azure-sdk-tools/pull/4940
> Add 'azure-load-testing' to MSServiceDoc

- docs/general/azurecore.md
Updating the General Guidelines with the outcome of the Architecture Board discussion on User-Agent string consistency across languages.
Arch Board issue: https://github.com/Azure/azure-sdk/issues/5110
> Update User-Agent guideline

- _data/releases/latest/dotnet-packages.csv
Add a missing link to the migration guide
> Add migration guide for Microsoft.Azure.Services.AppAuthentication

- _data/releases/latest/python-packages.csv
Update the CSV entry so the library is grouped with the following libraries:
> Change SDK name and service name in Python CSV

- _data/releases/latest/dotnet-packages.csv
The package is already marked as deprecated on nuget.org. Updating the CSV accordingly.
> Mark Microsoft.Azure.Management.Monitor NuGet package as deprecated

- docs/dotnet/introduction.md
- docs/dotnet/refs.md
> Add guidelines about .NET TFMs

- releases/2023-02/c.md
Similar change to https://github.com/Azure/azure-sdk/pull/5251
> Update latest embedded c release notes for Feb 2023 (no release)

- eng/scripts/BulkUpdatePackagePlannedDates.ps1
- eng/scripts/PackageList-Helpers.ps1
- eng/scripts/PackageVersion-Helpers.ps1
- eng/scripts/Query-Azure-Packages.ps1
- eng/scripts/Update-DevOps-WorkItems.ps1
- eng/scripts/Update-Release-Versions.ps1
Implements https://github.com/Azure/azure-sdk/issues/5565
> Add Needs Review for any new packages we add to csv

- _data/releases/2022-09/go.yml
- _data/releases/2023-02/go.yml
Fix links broken by https://github.com/Azure/azure-sdk-for-go/pull/20425
FYI @richardpark-msft
> Fix broken go example links

- eng/pipelines/version-updater.yml
- eng/scripts/Query-Azure-Packages.ps1
@mario-guerra I've setup the scheduled build to only run once on Sunday and in the pipeline here I'm only going to run the deprecation step only on Sunday. I've also provided a queue time parameter that we can use to manually queue a build that will run this step too.
> Only update deprecation status once a week on Sunday

- _data/releases/latest/java-packages.csv
Update CSV file for deprecation
> Azure Maps Elevation SDK Deprecation

- eng/scripts/Query-Azure-Packages.ps1
Also update message and deprecation reason for packages that have passed their EOLDate.
> account for deprecated packages with multiple replacements

- docs/cpp/introduction.md
> Add requirement for GetURL onto ServiceClients

- _includes/releases/variables/go.md
Fixes https://github.com/Azure/azure-sdk/issues/5997
> Update msdoc template for go to point at go dev

- docs/policies/releases.md
- docs/policies/reviewprocess.md
Fixing table formats so they display properly in https://azure.github.io/azure-sdk/policies_reviewprocess.html#1-introductory-session
Also found another table that was ot rendering correctly and extra information that I didn't delete properly last time.
> Update table format in Review process

- CONTRIBUTING.md
- _includes/releases/variables/dotnet.md
- _includes/releases/variables/java.md
- _includes/releases/variables/js.md
- _includes/releases/variables/python.md
Fixes https://github.com/Azure/azure-sdk/issues/5585
> Add preview prefix support for preview docs

- _includes/releases/variables/dotnet.md
- _includes/releases/variables/java.md
- _includes/releases/variables/js.md
- _includes/releases/variables/python.md
Fixes https://github.com/Azure/azure-sdk/issues/6064
> Add preserve-view to preview doc links

- .github/CODEOWNERS
Creating this PR as per suggestion from @jsquire in this issue: https://github.com/Azure/azure-sdk-tools/issues/5944
> update CODEOWNERS for SDK deprecation checking

- releases/2023-03/c.md
- releases/2023-04/c.md
- releases/2023-05/c.md
Similar change to https://github.com/Azure/azure-sdk/pull/5557
Follow-up from https://github.com/Azure/azure-sdk-blog/pull/395#issuecomment-1550479144
> Update latest embedded c release notes for March, April, and May 2023 (no release)

- docs/cpp/introduction.md
Details namespace should be _details
> Details namespace fix

- docs/cpp/introduction.md
https://github.com/Azure/azure-sdk/pull/6172#pullrequestreview-1451925000
> C++ guidelines: fix more instances of `_detail` namespace naming

- _data/releases/latest/js-packages.csv
PR to eliminate this row in the CSV:
> Change service name to Log Analytics

- _data/releases/latest/dotnet-packages.csv
Add Content Safety preview to dotnet csv
> Add Content Safety preview to dotnet csv

- _data/releases/latest/js-packages.csv
Call Automation is part of Azure Communication, updating to put this in the right place like other communication packages (like chat, rooms, etc)
> Update js-packages.csv for Call Automation

- docs/python/implementation.md
> [Python Guidelines] Update Enum To Remove Six

- _data/releases/latest/java-packages.csv
updating csv file for cleaning deprecation dashboard
> deprecated java package

- _data/releases/latest/js-packages.csv
fix docs missing for @azure/arm-appservice
> fix docs missing for @azure/arm-appservice

- _data/releases/latest/js-packages.csv
Was able to test with help from folks offline and looks as-expected to me:
- preview: https://review.learn.microsoft.com/en-us/javascript/api/@azure/functions/?view=azure-node-preview&branch=erijiz%2Ftest-azurefunctions
- latest: https://review.learn.microsoft.com/en-us/javascript/api/@azure/functions/?view=azure-node-latest&branch=erijiz%2Ftest-azurefunctions
> Add @azure/functions js package to docs

- _includes/releases/notes/common.md
Fixes https://github.com/Azure/azure-sdk-pr/issues/1523
> Only show header if there are packages

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Set epic work item type as Service or Product
> Set work item epic types for service and product

- eng/scripts/Query-Azure-Packages.ps1
See https://learn.microsoft.com/en-us/nuget/api/registration-base-url-resource#registration-page-object You may need to get all the item pages individually
> Need to handle paging for the list of versions for nuget package deprecation

- eng/scripts/Query-Azure-Packages.ps1
Fixes https://github.com/Azure/azure-sdk/issues/5368
> Remove error handling around maven so we know if it fails

- _data/releases/latest/python-packages.csv
Onboard azureml-featurestore package, which is not published via azure-sdk pipeline
Related PR: https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1825
> Onboard azureml-featurestore to doc gen

- docs/tracing/distributed-tracing-conventions.md
- docs/tracing/distributed-tracing-conventions.yml
Fixes https://github.com/Azure/azure-sdk-for-net/issues/39785
> Update Azure SDK semantic conventions and guidelines

- _data/releases/2023-11/dotnet.yml
@ArthurMa1978 any idea why these releases were removed?
> Hide removed releases

- eng/ci.yml
Testing for https://github.com/Azure/azure-sdk-tools/pull/7369
> Test changes to verify-link to remove 401 code

- eng/scripts/Query-Azure-Packages.ps1
Fix un intentional removal of scripts
> Revert unintended removal of params from query script

- _data/releases/latest/java-packages.csv
Health Insights Radiology Insights 1.0.0-beta.1 java SDK documentation release correction of ServiceName.
> Tomsft/bugfix/fix service name health insights radiology insights 1.0.0 beta.1

- docs/golang/introduction.md
- docs/golang/refs.md
Just a couple minor things I found while working on the Rust guidelines.
> Minor fix to Go docs

- .github/event-processor.config
Add EnforceMaxLifeOfIssues to event-processor.config set to Off
> Add EnforceMaxLifeOfIssues to config file set to Off

- .github/event-processor.config
Activate the EnforceMaxLifeOfIssues rule to auto close stale issues.
> Turn on EnforceMaxLifeOfIssues Rule

- docs/cpp/implementation.md
- docs/cpp/introduction.md
Cleaned up various sections of the guidelines.
Added some missing sections.
> Guideline cleanup

- _data/releases/latest/js-packages.csv
Copying from the Java CSV since these values are not populated for JS for some reason
> Update metadata for JS Event Grid Namespaces package

- _data/releases/latest/js-packages.csv
Allow @azure-rest/ai-inference to gen documentation
> [JS] [AI] [Inference] Allow @azure-rest/ai-inference to gen documentation in js-packages.csv

- docs/rust/introduction.md
- docs/rust/refs.md
Codifies https://github.com/Azure/azure-sdk-for-rust/pull/1705
> Put crate source in subdirs under service dir

- docs/typescript/approved_dependencies.md
Updates the list of approved dependencies to remove outdated packages that are no longer needed. 
Each removal will have a justification in the PR.
> [javascript] Update approved dependencies

- eng/pipelines/template/steps/generate-releasenotes.yml
Changing the secondFriday for September.
> Adding date change for Sept

- docs/rust/implementation.md
> Improve docs for Rust convenience methods

- docs/rust/implementation.md
- docs/rust/introduction.md
Resolves #7929 along with correcting any outdated directory structure documentation.
> Specify 1 crate per TypeSpec project

- docs/typescript/design.md
revisit pagination guideline in typescript.
> revisit-pagination-in-ts

- _data/releases/latest/python-packages.csv
Deprecated Python azure-cognitiveservices-language-spellcheck.
> Deprecate Python CS spellcheck

- _config.yml
- _data/releases/2021-08/dotnet.yml
- _data/releases/2021-08/python.yml
- docs/dotnet/implementation.md
GFM - Github Flavored Markdown
> Switch to using GFM for markdown

- docs/tracing/distributed-tracing-conventions.md
Attempt to fix https://github.com/Azure/azure-sdk/issues/8068
> Fix tables in MD page

- eng/scripts/Query-Azure-Packages.ps1
- Add retries based on Retry-After headers
- workaround issue with version comparsions
- Clean-up error logging
> Clean-up depecration code

- eng/pipelines/template/steps/generate-releasenotes.yml
This will update the release automation so on months where our releases are not following the normal pattern the release notes will now match the non-normal pattern.
> Updating release automation for 2025

- .github/CODEOWNERS
Changing the Java Release Notes Reviewer.
> Update Java Release Notes Reviewer

- releases/2024-11/index.md
- releases/2025-01/index.md
added link to blogs for november and january on the release pages
> Hector blog fixes

- _data/releases/2025-02/dotnet.yml
Remove broken links from .NET Release Notes
> Remove broken links from .NET Release Notes

- docs/rust/implementation.md
Resolves Azure/azure-sdk-for-rust#1796
> Document desugaring rust async traits

- releases/2020-11/python.md
- releases/2021-01/python.md
Fixing links broken by https://github.com/Azure/azure-sdk-for-python/pull/40712
fyi @swathipil
> Fix broken links caused by removed libraries

- .github/CODEOWNERS
Switching the Python Release driver from Xiang Yan to Kashif Khan
> Updating Python Release Driver

- _data/releases/2025-09/java.yml
Fix more broken links caused by https://github.com/Azure/azure-sdk-for-java/pull/46456/ 
cc @scottaddie
> Update migration guide links for deprecated package
