- docs/design/java/Versioning.md
This document discussed versioning of the Azure Java SDK and its components. It is intended to tease out some of the topics I'm overlooking but which are important for an SDK to be successful. I take an opinionated stance on how I would like to do things in Java (ignore side by side support, have end users opt-in to a version (or else get the latest version their downloaded library supports from when it was built), don't include version numbers in the package namespace, etc).
I have not thought much about the technical suggestions I provide at the end (and there are likely to be better ways we can determine when the detail is necessary), so don't dive too deeply into technicalities there.
I'd really appreciate feedback on things I'm misunderstanding or naively overlooking :-)
> Introduced a Java versioning discussion doc

- docs/design/Cancellations.mdk
- docs/design/OpenSource.mdk
- docs/design/Requirements.mdk
- docs/design/dotnet/DesignGuidelines.mdk
- docs/design/dotnet/DotNetSpec.mdk
Reorganized the document, added some clarifications, fixed misspellings, removed some sections that either don't add value or need to be clarified. 
I think this makes the .net guidelines doc ready for consumption.
> Reorganized .NET Guideline "Template"

- docs/design/Configuration.mdk
- docs/design/Requirements.mdk
- docs/design/dotnet/DotNetSpec.mdk
- docs/design/java/JavaSpec.mdk
Also fixes up a few typos I spotted along the way.
> Rearrange Java spec to follow the .NET spec lead

- .vscode/extensions.json
- .vscode/tasks.json
- package.json
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>B</kbd> builds the document by default now. You can optionally invoke watch which will run in the background and rebuild the document if any input source changes.
I've also added an extensions.json that recommends the madoko extension for syntax highlighting goodness.
> Add watch task and vscode config with recommended extensions

- docs/design/README.md
This mainly moves links to the guidelines to the top of the readme.
Also, it moves away from "specification" terminology to "guideline" and "document"
> Simplifying Design Guidelines Home Page

- README.md
Got some requests to bring back the JS template. It's there, but hard to find. This improves matters.
> Add links to templates for each language

- docs/design/OpenSource.mdk
- docs/design/typescript/DesignGuidelines.mdk
This promotes copyright headers and CLA requirements from TypeScript to the general guidelines (these are required by MS OSS Guidelines: https://docs.opensource.microsoft.com/).
> Add general requirement for copyright headers and CLA for contributions

- docs/engineering-system/repo-structure.md
After receiving more feedback I think it is better to group the packages under which service they apply to. This allows for each language to have a consist `sdk\<service name>` set of directories and it keeps all packages related to a particular service grouped together. I'd like to hear any further feedback from the various language teams before we update the associated issues and make this change.
https://github.com/azure/azure-sdk-for-net @shahabhijeet @AlexGhiondea -> https://github.com/Azure/azure-sdk-for-net/issues/5213
https://github.com/azure/azure-sdk-for-java @jianghaolu @mayurid -> https://github.com/Azure/azure-sdk-for-java/issues/2847
https://github.com/azure/azure-sdk-for-js @daschult @AlexGhiondea -> https://github.com/Azure/azure-sdk-for-js/issues/1138 …
> Revise the repo structure to group packages under related service

- docs/engineering-system/repo-branching.md
The following document outlines the general branching strategy we plan to use across our azure-sdk-for-* repos. 
Tagging the engineering system team and the leads for the azure-sdk teams:
@Azure/azure-sdk-eng 
@kurtzeborn @AlexGhiondea @mayurid 
@salameer @sphibbs @lmazuel @yugangw-msft
Please review the document and provide feedback and add any additional reviews as needed.
> Add document outlining our repo branching strategy

- docs/design/java/DesignGuidelines.mdk
- docs/design/java/JavaSpec.mdk
* Introduce more spec requirements around code structure, naming patterns, and exception handling
* Rename from 'sdk components' to 'client libraries'
> Update Java spec

- docs/design/DesignGuidelines.mdk
- docs/design/Pagination.mdk
- docs/design/components.mdk
- docs/design/typescript/TypeScriptSpec.mdk
This supplants the gist discussion from earlier. I've put the controversial guidelines in a draft section. Maybe we can reach consensus on GitHub? For clarity, we the contentious items (indexes from the gist are preserved 😄)
1. Expose non-paginated APIs as paginated APIs so client changes don't break us
2. ~~Expose APIs to get all the items at a paginated endpoint into an array~~
3. Expose low-level paging APIs that enable a more manual traversal process
> [General] Add pagination guidelines

- docs/engineering-system/releases.md
This is an initial stab at how we want to handle the SDK release process including preview releases. A LOT of stuff is outstanding/not determined here and I'm sure there will be tons of opinions. Send me your thoughts!
Some issues to think about:
+ ~~Do we need to support daily, beta, and RC releases? Opinions seem divided about this. Do we just have one kind of 'preview' release? Is that one kind of preview a daily?~~
+ Just using 'Daily' and 'Preview'
+ ~~@weshaggard was pretty set on having .NET just do daily and then actual releases. Wes - do you have the algorithm you were using to generate day numbers as short's for me?~~
+ See above
+ ~~Can we require that all libraries have a 'next expected release date' in the README? this might be the easiest guideline to provide?~~
+ Guidance …
> initial release guidance

- docs/engineering-system/releases.md
Only part in contention will probably be:
```
<content. as long as it doesn't introduce another header that looks like the one above>
...additional changelog entries
```
Does anyone have a problem with this style?
> Adding ChangeLog Guidance

- docs/engineering-system/releases.md
This mirrors the method that we currently use for the `javadocs` and `sources` artifacts.
> Java ChangeLog Guidance Adjustment

- README.md
- docs/design/OpenSource.mdk
Now that we taking a dependency on 2.0 packages, we should just simplify and and let the < 4.7.2 problem phase out.
> moving readme template links into the design guidelines.

- docs/engineering-system/releases.md
@maggiepint using the date for .NET works pretty well so updating to doc.
In case you are interested the implementation for this in the .NET repo is https://github.com/Azure/azure-sdk-for-net/pull/6237
> Update .NET package version to use date and revision

- docs/design/general/Pagination.mdk
When the pagination guidelines were updated, there was a conflicting guideline, basically saying the opposite of the revised guidelines.  Removing the conflicting guidelines so that the intent is correct.
> Removed conflicting language from the pagination guidelines

- docs/design/Cancellations.mdk
The header `Cancellation & Timeouts` had me thinking that both needed to implemented as 2 separate options i.e provide cancellation token as well as a separate timeout option.
On discussion with @bterlson, it was clarified that the cancellation mechanism is expected to have the timeout logic in it and a separate timeout is not needed.
This PR is to update the header to clarify this.
> Update to clarify that cancellation and timeouts are not separate entities

- docs/design/typescript/DesignGuidelines.mdk
Implements minor changes to the TypeScript-specific guidelines:
- Creates the `ts-package-json-module` and `ts-error-handling` rule IDs for existing rules
- Upgrades the requirement that TypeScript be used from "Should" to "Must"
- Marks usage of the `@azure/core-configuration` package as a TODO (package does not exist yet)
- In `ts-package-json-repo`, changes the monorepo link from this repository's link to the JavaScript/Typescript-specific monorepo
- Renames `ts-config-sourceMaps` to `ts-config-sourceMap` and accordingly for any instance of the string `sourceMaps` (typo)
> TypeScript guidelines minor fixes/updates

- docs/README-TEMPLATE.md
The CI process which verifies README.md for client libraries now requires the 'Contributing' section.  This changes adds this section to the README-TEMPLATE.md
> Updating README-TEMPLATE.md to contain 'Contributing' section

- README.md
We didn't have links to the general guideline rendering, only the language ones.
> Add link to general design guidelines

- docs/design/dotnet/DesignGuidelines.mdk
> Renaming ConfigurationClientModelFactory to ConfigurationModelFactory

- docs/release-notes/preview/high-level-relnote-template.md
Library packages are released one at a time or many at once. When
multiple are being released at once, this template should be used
to provide easy jumping off pointers and information about the set of
packages in the group.
To use it, fill in the details in the TODOs and copy in a versioned
folder in the release-notes directory of the Azure-SDK repository.
> Create multi-library release note template

- docs/release-notes/preview/summary-preview1-java.md
This PR updates the docs with the new location for app configuration. This PR should only be merged after this PR in the Java repo:
https://github.com/Azure/azure-sdk-for-java/pull/4307
> Updated README and samples location for appconfiguration.

- docs/design/general/DesignPrinciples.mdk
The current guidelines is pushing feature teams to adapt non-idiomatic solutions in the name of cross language consistency. I'm also finding myself much more closely aligned between the service and it's corresponding client library than I am cross client library for the same service.
By anchoring against the service terminology and behavior, the client libraries **should** end up being consistent in the areas where it matters the most.
> Bump importance of client library <-> service consistency over cross-language consistency

- docs/design/components.mdk
- docs/design/general/custom.css
This PR 
1. Adds role='img" and descriptive aria-label tags to the hyperlinked emoji's for screen readers.
2. Updates the code style to follow a GitHub-like highlighted gray-box style for **code**
> Adding accessibility for emoji's and updating code style

- package.json
chokidar-cli relies on lodash < 4.17.12, which means it has a high-risk security vulnerability.  Disabling the watch capability until we can get an alternate file watcher going.
> (#503) Removed chokidar-cli (security issues)

- _posts/2019-08-06-dotnet-preview2.md
The intent of these changes is to provide an additional bullet in the Event Hubs section, highlighting  the new iterator pattern for consuming events.
Wednesday, August 7, 2019  3:13pm (EDT)
> [Preview Two] .NET Release Notes

- docs/java/approved_dependencies.md
- docs/java/design.md
- docs/java/documentation.md
- docs/java/refs.md
* Reactor and Netty should no longer be part of the public API
* Return type for sync collections is no longer Stream - it is either PagedIterable or IterableStream (depending on ability to move by page).
* Changing API design for all methods to now be prefixed with get / set / is / etc, except in the case of service client builder classes, which can drop the prefix.
* Fixes for typos, formatting, and bad links.
> Updating Java spec guidelines

- docs/java/approved_dependencies.md
- docs/java/design.md
Also, make fluent model classes return 'this' in the setter methods.
> Reactor is allowed in public API

- Gemfile
- _config.yml
- _data/sidebars/dotnet_sidebar.yml
- docs/dotnet/implementation.md
- docs/dotnet/introduction.md
- docs/dotnet/refs.md
Relates to Azure/azure-sdk-for-net#7547 and should be merged only after PR Azure/azure-sdk-for-net#7569 is merged.
> Add guideline about using a common argument validator

- docs/clang/documentation.md
This resolves one of the TODOs in #647 
it goes over how to reference example files, including how to include them in documentation, how to link to them, and how to include just portions of them.
> add documentation example for examples/snippets

- Gemfile
- Gemfile.lock
1) dnsruby & nokogiri are now included in latest Jekyll, so removed explicit reference.
2) bundle update fixes the rubyzip security issue
> Updated Gem bundle for security updates

- docs/general/azurecore.md
Service teams (particularly Cosmos) requested some additional requirements around the application ID.  This request adds two requirements:
1) That the user be able to specify the application ID within the client options bag when constructing a service client
2) That we support up to 24 characters for the consumer selected application ID.
> (#584) Added user-agent / telemetry additional requirements

- releases/2019-10-11/2019-10-11-dotnet-preview4.md
The focus of these changes is to update the release notes for the Event Hubs client with highlights from the fourth preview and to ensure that each of the  associated asset links is valid.
Friday, October 11, 3:46pm (EDT)
> .NET Release for Preview 4: Updating Event Hubs Release Notes

- releases/2019-10-11/2019-10-11-dotnet-preview4.md
The focus of these changes is to update the Event Hubs package version in the example snippet for adding references.  It was overlooked when submitting the change log.
Friday, October 11, 5:03pm (EDT)
> Event Hubs: Update reference example

- docs/policies/releases.md
Following policy and correcting spelling error from last push.
> Fix spelling of 'dependencies'

- docs/clang/implementation.md
change the clang-format command line to use -style=file instead of -style=llvm. This causes clang-format to look for a .clang-format file in parent directories of the targeted source file.
> clang format use file

- releases/2019-11/2019-11-dotnet.md
The focus of these changes is to update the release notes for the Event Hubs client with highlights from the fifth preview and to ensure that each of the associated asset links is valid.
Thursday, October 31, 9:428am (EDT)
- [Release Event Hubs Track 2 Library Preview 5 for .Net ](https://github.com/Azure/azure-sdk-for-net/issues/8190) (#8190) 
- [Review and update documentation ](https://github.com/Azure/azure-sdk-for-net/issues/8191) (#8191)
> .NET Release for November: Event Hubs Release Notes

- docs/clang/documentation.md
fixes one of the todos in #647 
This is the same code as included in the prototype project template in the Azure/azure-sdk-for-c repo.
> add an example for doxygen usage in cmake

- releases/2019-11/2019-11-dotnet.md
Small typo fix in the release notes for EventHubs
> Event Hubs: Fixing typo in release notes

- _includes/tables/environment_variables.md
The environment variables AZURE_CLOUD, AZURE_SUBSCRIPTION_ID, and AZURE_RESOURCE_GROUP are environment variables which impact multiple client libraries across the SDK and are not Identity specific. Furthermore AZURE_SUBSCRIPTION_ID and AZURE_RESOURCE_GROUP don't apply to Identity at all.
> Move general config env variables out of Identitiy

- docs/policies/releases.md
1. Updated dev build format
2. Updated version guideline for python after GA
3. Updated version guideline for hotfix release for Python
> versioning changes guidelines for python after GA

- docs/clang/implementation.md
The authentication section is a bit spartan right now, but I've added a guideline that you must use special secure zeroing functions to clear credentials from memory.
> add guideline on using secure zeroing functions

- docs/clang/implementation.md
clang's Weverything is like our (msvc's) /Wall, it's REALLY everything, and it's not designed to be used day to day, definitely not as a MUST default.
> Don't use Weverything.

- docs/clang/implementation.md
- add example for the anti goto fail guideline
- remove several formatting guidelines that clang-format can deal with
- change guidance on yoda style to be "don't use it" (we discussed this some time ago, and came to the conclusion the "natural" style is fine with compiler warnings for `if (a = 1)` constructs.
> formatting section changes, no yoda anymore

- releases/2019-12/2019-12-dotnet.md
The focus of these changes it to provide changelog details for the Event Hubs client library for .NET.
Wednesday, December 4, 3:12pm (EST)
> December Release Notes for .NET

- _includes/python-packages.html
- eng/scripts/Update-Release-Versions.ps1
We fixed the packages that needed this hack/workaround so
we can remove the workaround now.
> Remove the PackageOverridePath from python template

- docs/clang/implementation.md
After discussion on friday the 15th we came to the conclusion that it indeed does not make any sense to have run-time configuration for the c sdk via config files or env vars. IOT clients probably won't even have a filesystem of environment block.
Note that the client can still be configured at runtime, but only by the user/caller, not by the client librariy itself.
> no runtime configuration for c.

- docs/dotnet/introduction.md
This guideline update clarifies what we have been doing already, i.e. we reserved the ServiceVersion value 0, mainly so people don't accidentally pass in the default value.
> Clarified ServiceVersion Guidelines

- docs/policies/releases.md
We recently had some discussion around which tags (latest, next, dev) should be used in which scenarios. This PR attempts to capture the notes from that discussion in the guidelines.
> JS: Guidelines for tags to use

- _data/releases/latest/dotnet-packages.csv
The focus of these changes is to add a line item for the Event Hubs package for the Event Processor client.
Monday, December 9, 9:33am (EST)
> Release Package List - Adding Event Hubs: Event Processor

- docs/clang/design.md
- docs/clang/implementation.md
* also cleans up some misc things that I found reading through the document.
> Add guidance on naming for private constants

- docs/policies/releases.md
In order to have consistent CHANGELOG.md format, I am updating the changelog guidance using input I have gotten from several people. This PR is to give all language leads an opportunity to agree on how changelogs should be formatted so that it can properly be enforced be Doc Warden for all languages.
@weshaggard @ramya-rao-a @mayurid @lmazuel @praveenkuttappan @AlexGhiondea @scbedd @joshfree @jonathangiles
General guidance is takenfrom https://keepachangelog.com/en/1.0.0/
> Update Changelog Guidance

- _posts/2019-11-11-november-ga-release.md
- _posts/2019-12-13-december-release.md
Added a page describing what was completed in December with pointers to the latest release notes for December to appear as the top item on the homepage.
Fixed a typo in the November post at the same time.
> Add December release to home page, fix typo

- docs/clang/implementation.md
The Coding Style/Files section was somewhat out of sync with what we have agreed to do, and what the sdk team is actually doing. This brings it into alignment and adds guidance on "internal" headers, that is headers exposed to other sdks but not part of the public API.
> Add guidence on internal headers per our recent meetings.

- releases/2019-12/2019-12-dotnet.md
- releases/2019-12/2019-12-java.md
- releases/2019-12/2019-12-js.md
- releases/2019-12/2019-12-python.md
- releases/2020-01/dotnet.md
- releases/2020-01/java.md
- releases/2020-01/js.md
- releases/2020-01/python.md
Less confusing for 2019-12 and 2020-01 that use the latest data source.
> Change Quick Links to Latest Releases

- releases/2020-01/java.md
5.0.1 for Event Hubs and 1.0.1 for Checkpoint Store is not yet released. Updating the version to previous release version until the new versions are released.
> Update Event Hubs version

- _data/sidebars/android_sidebar.yml
- _data/sidebars/clang_sidebar.yml
- _data/sidebars/cpp_sidebar.yml
- _data/sidebars/dotnet_sidebar.yml
- _data/sidebars/general_sidebar.yml
- _data/sidebars/golang_sidebar.yml
- _data/sidebars/home_sidebar.yml
- _data/sidebars/ios_sidebar.yml
- _data/sidebars/java_sidebar.yml
- _data/sidebars/js_sidebar.yml
- _data/sidebars/python_sidebar.yml
- docs/policies/pipelines.md
This PR adds some notes about our pipeline structure. One thing that it calls out specifically is some guidance around what should be in and what should be out of the pipelines. Mostly inspired by lessons learned about having repo-wide analysis steps.
> Add notes about pipeline structure.

- docs/java/implementation.md
Logging guidance in the Java design guidelines had fallen behind the general guidelines, and was inconsistent with the actual API being offered (which was based on the general guidance). This is a copy / paste of the general guidelines into the java guidelines, replacing the old guidance (particularly around level naming (trace -> verbose)).
Fixes #636
> Updating logging guidance

- releases/2020-03/dotnet.md
Key Vault has released both servicing and preview versions of its libraries at different versions in some cases. I tried to consolidate as much as reasonable.
> Add release notes for Key Vault for .NET

- docs/clang/design.md
* change from PascalCase to snake_case for enums
* add requirement for enumerator names
* use typedef enum in examples
* weaken guidance on where to put an "error" value from MUST to SHOULD
> revise guidence on enums

- docs/general/design.md
- docs/general/implementation.md
From the arch board notes:
**ACTION**: Add the following requirements to general guidelines
* GA libraries MUST target GA service API versions.
* LATEST in GA library MUST point to the latest GA service API version.
* Public preview versions of the library MUST point to latest public preview service API version.
* Client libraries MUST include all versions of the service API that the client library supports in a ServiceVersion enum.
* Client libraries MUST document what "latest service API version" points to.
*ServiceVersion enum values MUST match the service version in swagger.
**ACTION**: Update the Recorded tests section as follows:
* Replace "DO recreate recorded tests for a specific service version" with "DO create recorded tests for the latest service version"
> (#1043) Updates to guidelines from arch.board meeting

- eng/ci.yml
- eng/githubio-linkcheck.yml
Added --ignore-url "https://www.linuxmint.com/download_all.php"
to help with the reliability of our linkchecking task as it seems
to timeout often.
> linuxmint.com often times out so ignore checking it

- _posts/2020-03-31-aspnet-core-integration.md
cc @adrianhall @pakrym 
For whatever reason this link doesn't correctly resolve in the live site. It resolves to https://azure.github.io/posts/2020-02-25/defaultazurecredentials.html instead of https://azure.github.io/azure-sdk/posts/2020-02-25/defaultazurecredentials.html so I'm just going to put the full link.
> Update link to post

- releases/2020-04/dotnet.md
The focus of these changes is to update the April milestone release notes with the Event Hubs details.
Friday, April 3, 4:12pm (EDT)
> [April Release Notes] Event Hubs Client

- releases/2020-04/dotnet.md
The focus of these changes is to include the installation instructions for Event Hubs.
Friday, April 3, 5:26pm (EDT)
> [April Release Notes] Event Hubs Installation Instructions

- docs/cpp/design.md
Always fun when Bill makes mistakes that completely invert the meaning :)
> Fix MUST/MUSTNOT typo that contradicted the examples in C++ design.md.

- _includes/releases/all/dotnet.md
- _includes/releases/all/java.md
- _includes/releases/all/js.md
- _includes/releases/all/python.md
- _includes/releases/dotnet.md
- _includes/releases/header.md
- _includes/releases/java.md
- _includes/releases/js.md
- _includes/releases/python.md
- releases/latest/all/dotnet.md
- releases/latest/all/index.md
- releases/latest/all/java.md
- releases/latest/all/js.md
- releases/latest/all/python.md
- releases/latest/dotnet.md
- releases/latest/index.md
- releases/latest/java.md
- releases/latest/js.md
- releases/latest/python.md
1. Added /releases/latest/all page so we can easily link to via aka.ms links (i.e. aka.ms/azsdk#java)
1. Removed "Packages" from header to get simplified language only anchor tags #java instead of #java-packages
1. Refactored to put package lists in include files
1. Added "Azure SDK Latest Releases" to each page to be consistent
1. Changed language headings from # to ## to be consistent across pages
> Add all packages page and refactor

- docs/cpp/design.md
…following 2020-04-09 affirmation of always using pragma once.
> [cpp] Remove header guards from acceptable uses of macros 

- docs/python/design.md
I believe it's a typo here: `dowload` -> `download`
> Fix typo in Python design.md

- _includes/tables/environment_variables.md
All SDKs now support the AZURE_AUTHORITY_HOST environment variable, which allows developers to override the default 'https://login.microsoftonline.com' value with an endpoint appropriate for their environment.
> Add authority host to list of environment variables

- docs/typescript/implementation.md
Over in https://github.com/Azure/azure-sdk-for-js/pull/7615 we discovered that inlineSourcemaps are easier to get right inside our package, especially for transitive dependencies like core-http. Separately, over in https://github.com/Azure/azure-sdk-for-js/issues/7706, we've found that including `tsconfig.json` in the package isn't particularly useful when the `tsconfig` is tied to our monorepo structure.
High level modifications:
* Don't ship `tsconfig.json` in your package
* Include original source inside sourcemap files generated by tsc.
> Updates for inlineSourcemaps

- releases/2020-05/dotnet.md
The focus of these changes is to add the Event Hubs sections to the May release notes.
Friday, May 1, 1:48pm (EDT)
> [May Release Notes] Event Hubs

- eng/scripts/Verify-Links.ps1
If the file exists read the contents even if it
is not a known file extension.
> Allow link checker to open other file types

- docs/general/implementation.md
Resolves #1199
As called out in the bug, there are demonstrated cases where not validating null or empty path parameters can result in a request for a different resource(s) which can result in a confusing deserialization error or, at worst, deletion of other or more resources than desired.
> Update client parameter validation requirements

- releases/2020-05/java.md
This month we only updated the azure-core versions and fixed a bug, hence why no changelog section was added.
> Updated Java README for the KeyVault May 2020 release.

- eng/pipelines/generate-release-structure.yml
- eng/scripts/Generate-Release-Structure.ps1
- eng/scripts/release-template/dotnet.md
- eng/scripts/release-template/index.md
- eng/scripts/release-template/java.md
- eng/scripts/release-template/js.md
- eng/scripts/release-template/python.md
PTAL @czubair @adrianhall 
This adds some automation for generating a new release folder for the next month. 
Running the [pipeline ](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1745&_a=summary) will generate a PR like https://github.com/Azure/azure-sdk/pull/1375
> Add automation for generating a new month's release structure

- _includes/releases/all/pkgtable.md
- _includes/releases/header.md
- _includes/releases/pkgtable.md
- js/customscripts.js
PTAL @jongio I only did this for the all package indexes but we could just as easily add it everywhere. 
Here is a sample screenshot of the filtering at work.
> Add basic filtering to the all libaries package index pages

- releases/2020-06/python.md
This is a special-ish case because we have both GA and preview of TA releasing this month (preview was released out of band 2 weeks ago). Let me know if this setup is correct!
> TA GA release notes 2020-06

- releases/2020-07/dotnet.md
The focus of these changes is to add the Event Hubs details to the July release notes for .NET.
Wednesday, July 1, 5:27pm (EDT)
- [Review and update documentation (July Milestone)](https://github.com/Azure/azure-sdk-for-net/issues/11746) (#11746)
> [July Release Notes for .NET] Event Hubs

- docs/java/design.md
- docs/java/implementation.md
* Updated Java spec to spell out expectation that all pipeline policies be public API to allow for end users to reuse them in other pipelines.
* Added version numbering guidelines (from C# guidelines).
> Add requirement that pipeline policies be public API for consumer reuse.

- docs/clang/implementation.md
Explicitly adding documentation about how to declare and use an internal structure in a public header 
This is how it looks:
> Adding guidance about how to use internal structures on public headers

- docs/policies/releases.md
@weshaggard - From my conversation with @ahsonkhan, we'd like to propose reverting the tagging back to `<version>` only instead of `<repo-name>_<version>`.
> Update language to refer to new release tag formatting

- docs/policies/README-TEMPLATE.md
- adding workarounds for link verification in ci and reasoning for link guidance update
> adding workarounds and reasoning for link guidance update

- releases/2020-08/dotnet.md
The focus of these changes is to add the Event Hubs content for the August release notes.
Friday, August 7, 12:23pm (EDT)
> [August Release Notes] Event Hubs

- docs/typescript/design.md
This is still using `preview` nomenclature as I've yet to update to `prerelease` globally.
> Use standard npm distribution tags

- docs/dotnet/implementation.md
This was from an internal discussion, and is being used for Search's `FieldBuilder`.
> Add example of extensible enum constants

- releases/2020-09/dotnet.md
Adding the Event Hubs content to the release notes for September.
Thursday, September 3, 5:48pm (EDT)
> [Sepember Release Notes] Event Hubs

- releases/2020-09/python.md
@xiangyan99  I copied the pattern from prior releases (march) where checkpointstoreblob did not note itself at the top level, only denoting "EventHubs".  Just pointing this out as it's novel for me, to ensure I've kept all proper notation.
>  Add Python Event Hubs CheckpointStoreBlob 1.1.1 (September) release notes

- releases/2020-09/js.md
September release notes for JavaScript.
The previous one was: https://github.com/Azure/azure-sdk/pull/1629
> [JS] September release notes

- releases/2020-09/dotnet.md
- releases/2020-09/index.md
- releases/2020-09/python.md
As discussed offline, we do not want to announce the Schema Registry packages as the service is still in private preview.
We should move this to the next month
> Schema Registry not ready for announcement

- docs/policies/releasenotes.md
We have confusion around where out of band release notes belong, from both our team and partner teams.  This update will hopefully make the guidance simple and solve a few problems that we are experiencing.
Our current guidance states that out of band releases go in the "next month's" release notes, but this creates a problem for us because:
1. In order to expose those notes, we have to publish the next month release files before the next month.  i.e., we need to release and announce something on 9/22, blog, tweet, etc.  But the release notes would be in Oct (under the current guidance)
2. This makes it look like we didn't ship much in October, because it only has the release notes of the out of band releases.
This update changes that guidance to put the out of band release notes in the …
> Update Out of Band Release Notes Policy

- _data/releases/latest/java-packages.csv
This PR adds newer client libraries of Digital Twins service to track in releases.
https://azure.github.io/azure-sdk-for-java/communication.html
> Update java-packages.csv to include Digital Twins

- releases/2020-10/dotnet.md
The focus of these changes is to add the Event Hubs information into the October release notes.
Tuesday, September 29, 11:22am (EDT)
> [Octoboer Release Notes] Event Hubs

- releases/2020-09/java.md
Add release notes for beta release of Event Hubs that happened last week.  This release was out of band. A new feature was added to support creating an idempotent producer.
> Sep release notes for EH preview release

- releases/2020-10/dotnet.md
The focus of these changes is to update the Event Hubs package version for October.
Wednesday, September 30, 11:36am (EDT)
> [Release Notes]  Event Hubs, Part II

- releases/2020-09/c.md
Following up on https://github.com/Azure/azure-sdk/pull/1818#discussion_r497028422
> Change header value for changelog sub-headings from 4 to 3 to be consistent.

- docs/typescript/design.md
This new guideline is consistent with what we have been doing so far and our ESLint plugin implements it.
> [TypeScript] Adding a guideline on naming the type of the options bag

- releases/2020-10/js.md
October release notes for JavaScript.
If you're looking for inspiration, the PR for the September release was: https://github.com/Azure/azure-sdk/pull/1750
> [JS] October release notes

- eng/scripts/release-template/android.md
- eng/scripts/release-template/c.md
- eng/scripts/release-template/cpp.md
- eng/scripts/release-template/dotnet.md
- eng/scripts/release-template/ios.md
- eng/scripts/release-template/java.md
- eng/scripts/release-template/js.md
- eng/scripts/release-template/python.md
- releases/2020-10/js.md
Updating the release notes for JS to not have quick links as we dont render these anymore
> We dont have quick links anymore

- releases/2020-10/index.md
I noticed that links to the release notes for mobile libraries had not been included in the latest [release blog](https://devblogs.microsoft.com/azure-sdk/october-2020-release/). They already exist in the `index.md` template located at `eng/scripts/release-template` so future releases won't be impacted, but the changes were added after the October's index file had already been generated. @jongio will update October's blog after these changes are included :)
> Added links for Android and iOS in the October release notes index.

- releases/2020-10/dotnet.md
This link was broken by the rename in https://github.com/Azure/azure-sdk-for-net/pull/16056
> Fix broken link to opentelemetry change log

- _includes/sidebar.html
the new Search functionality dependency on a different Jquery package broke existing functionality on pages where the side bar exists such as deep links. the search functionality is compatible with the existing Jquery version included in the project.
You can test my changes deployed in my fork here:
https://salameer.github.io/azure-sdk/dotnet_introduction.html#dotnet-principles
Look for the anchor icon that disappeared when hovering over a section. you should now see it as in this snapshot
> Deep links broken

- docs/tables/registered_namespaces.md
Ink Recognizer links no longer exists on azure and the docs also call out that it is being retired https://docs.microsoft.com/en-us/azure/cognitive-services/ink-recognizer/.
FYI @KrzysztofCwalina @JeffreyRichter  I'm removing this because the links are broken. If you would prefer that I leave it and replace it with another link or no link let me know.
> Remove Ink Recognizer

- releases/2020-11/dotnet.md
The focus of these changes is to add the release notes for the November Event Hubs release.
Monday, November 9, 3:48pm (EST)
> [Release Notes] Event Hubs: November

- _data/releases/latest/dotnet-packages.csv
Microsoft.Extensions.Azure moved from core to extensions directory
between 1.0.0 GA and 1.1.0-beta.1 and so those 2 versions have different 
source patterns and thus we cannot have valid links for both of them in 
the index system, so for now until 1.1.0 GA's we are hiding this package from the index. 
FYI @pakrym
> Hide Microsoft.Extensions.Azure until next GA

- _includes/releases/pkgbadge.md
- css/customstyles.css
Suggested change for the team to consider and maybe vote.
Motivation: Trying to make the table smaller for mobile view and small screens.
fixes: https://github.com/Azure/azure-sdk/issues/2022
After the fix, the table looks like:
Instead of looking like:
> avoid expanding the preview buttons and wrap them

- releases/2020-11/js.md
November release notes for JavaScript.
If you're looking for inspiration:
- Highlight guidelines: https://azure.github.io/azure-sdk/policies_releasenotes.html
- September's PR: https://github.com/Azure/azure-sdk/pull/1750
- October's PR: https://github.com/Azure/azure-sdk/pull/1878
This PR comes from https://github.com/azure-sdk/azure-sdk/pull/1
> November release highlights for TypeScript

- docs/typescript/design.md
Node has moved forward with 14 being the latest LTS. Instead of having to update the guidelines constantly to keep up, I removed the specific example to match how we handle browser versioning.
> [ts] Remove specific node numbers from docs

- releases/2020-11/dotnet.md
- releases/2020-11/java.md
- releases/2020-11/js.md
- releases/2020-11/python.md
This includes .NET, Python, Java and JS.
Communication Administration has seen the biggest changes, the other libraries had only minor updates.
> Communication release notes 2020-11

- releases/2020-11/java.md
Remove aad related release notes because the release of AAD starter was cancelled, refering to https://github.com/Azure/azure-sdk-for-java/pull/17820
> Update release notes of spring boot

- docs/dotnet/introduction.md
The focus of this proposed change is to provide more clarity to the behavior of the `Value` property of `Operation<T>`, specifically with regard to exceptions.
This guidance is currently implied only in the code LRO code example and the exception behavior comes up frequently in code reviews.
> Add more clarity to LRO guidelines regarding exception behavior

- docs/typescript/design.md
- docs/typescript/implementation.md
Per the MQ Guidelines initiative to fill gaps in the guidelines across languages, we are moving to a new common structure for the guidelines and calling out areas where there are content gaps -- i.e. one or more of he other language guidelines have guidance that is not language-specific that is not represented in this language's guidelines.  
This corresponds to the following work items:
- https://github.com/Azure/azure-sdk/issues/2104 Move Introduction and Documentation sections into Design and Implementation sections
- https://github.com/Azure/azure-sdk/issues/2108 Fit content to new Guidelines structure
- https://github.com/Azure/azure-sdk/issues/2110 Add code samples to guidelines sections
- https://github.com/Azure/azure-sdk/issues/2111 Make general guidelines more …
> MQ Guidelines Initiative: JS/TS TODOs

- docs/python/design.md
Per the MQ Guidelines initiative to fill gaps in the guidelines across languages, we are moving to a new common structure for the guidelines and calling out areas where there are content gaps -- i.e. one or more of he other language guidelines have guidance that is not language-specific that is not represented in this language's guidelines.  
This corresponds to the following work items:
- https://github.com/Azure/azure-sdk/issues/2100 Move Introduction and Documentation sections into Design and Implementation sections
- https://github.com/Azure/azure-sdk/issues/2101 Fit content to new structure
- https://github.com/Azure/azure-sdk/issues/2102 Add code samples to guidelines sections
> MQ Guidelines Initiative: Python TODOs 

- _data/releases/latest/java-packages.csv
- eng/scripts/Update-DevOps-WorkItems.ps1
If we release more then one version in a day the script can sometimes
cause the order to be alternating so sort by version as well.
Mark one more java package as replaced to remove it from the list
we process.
> Fix script sorting

- docs/typescript/implementation.md
Realized I never deleted this guidance. This change brings the guidelines in line with what we arrived at a week before the November GA releases.
> Remove requirements for browser bundles

- _includes/releases/variables/dotnet.md
- eng/scripts/Update-Release-Versions.ps1
We have unified .NET blob storage index.html path to align with other lang repo. There is no need of special handling here.
> Remove special handling for .net Github IO path

- _data/releases/latest/js-packages.csv
Since JavaScript doesn't have just one core package, it makes sense to move core-http out of the "Core" folder/section.
> [Core - HTTP] Title fix for the JavaScript work item

- _includes/tables/environment_variables.md
- docs/clang/design.md
Const members in structs make initialization much harder, and don't offer much in the way of added safety. Issues with them have come up multiple times during development.
> Ban Const members of structs

- docs/clang/design.md
This is more of an implementation detail, it doesn't affect the actual API, but it appears in the API function signatures so I put it in the API design section, since that's where the programmer will be looking when this question comes up.
This prohibits all "first level" const in function signatures and return types, since they don't really do anything and have persistently caused confusion.
> clang, prohibit first level const in function signatures

- .github/CODEOWNERS
> Add deputy architects to CODEOWNERS file.

- docs/typescript/design.md
This codifies what we've been doing in JS which is a little different because sometimes we have a model type with `etag` on it, but sometimes we don't, in which case the user needs a way to just give us the etag value.
> conditional requests guidelines

- docs/typescript/design.md
The namespacing guidelines aren't relevant as stated without the browser bundles exposing namespaces, so I removed it. Cleaned up a few other guidelines, and added a section around service versioning too.
(Sorry this is a little messy, I've decided to break up my many cleanups/updates into smaller chunks for easier reviewing).
> Packaging & versioning cleanup

- releases/2020-12/js.md
December release notes for JavaScript.
If you're looking for inspiration:
- Highlight guidelines: https://azure.github.io/azure-sdk/policies_releasenotes.html
- September's PR: https://github.com/Azure/azure-sdk/pull/1750
- October's PR: https://github.com/Azure/azure-sdk/pull/1878
- November's PR: https://github.com/Azure/azure-sdk/pull/2029
> December release highlights for JavaScript & TypeScript

- _data/releases/latest/js-packages.csv
- _data/releases/latest/python-packages.csv
For Python and JS, the track 2 packages that just went GA are the same package as track 1 with just the major version update. So, the note on "replacing" is not needed.
Found during https://github.com/azure/azure-sdk-for-js/issues/12376 by @richardpark-msft
> Remove 'will replace' notes for SB 

- _data/releases/latest/js-packages.csv
"LRO" makes more sense to me than "lro".
In case anybody reads this and is unaware of the context, LRO means Long Running Operations.
> "lro" to "LRO" on js-packages.csv

- docs/dotnet/implementation.md
- docs/dotnet/introduction.md
Fixes several broken links in Design and Implementation pages in the .NET guidelines.
Fixes #2228
> Fix broken links in .NET Guidelines

- eng/ci.yml
Pin ruby to last functioning version 2.7.2 to unblock pipeline.
> Pin Ruby version to 2.7.2

- releases/2021-01/js.md
January release notes for JavaScript and TypeScript.
If you're looking for inspiration:
- [What's a Developer Impacting Change?](https://github.com/Azure/azure-sdk/blob/08f279b39a4c19822b1509e6b10fc3ce256607b5/docs/policies/releasenotes.md#whats-a-developer-impacting-change).
- Highlight guidelines: <https://azure.github.io/azure-sdk/policies_releasenotes.html>
- September's PR: #1750
- October's PR: #1878
- November's PR: #2029
- December's PR: #2138
> January release highlights for JavaScript & TypeScript

- docs/android/implementation.md
- docs/java/implementation.md
- docs/java/introduction.md
This PR updates:
- logging guidelines to use the correct APIs. The current guideline refers to `ClientLogger.logAndThrow()` API which does not exist in `ClientLogger`. This PR changes the codesnippet in the guideline to use APIs that exist in `ClientLogger` like `logExceptionAs*` and `logThrowableAs*`.
- fluent setter method guidelins for subclasses
> Update guidelines for logger and fluent setter method for subclasses

- docs/golang/design.md
- docs/golang/implementation.md
- docs/golang/introduction.md
- docs/golang/packages.md
This moves the content to follow the template used across all languages.
Topics that have not yet been covered by the guidelines were left with a
TODO comment with rare exception.
No existing content was changed in any way.
> Refactor Go design guidelines

- _includes/tables/data_namespaces.md
- docs/java/introduction.md
This PR updates Java guidelines:
- To explicitly state not to include `azure-identity` as a dependency
- Add `quantum` as an approved namespace
- Static method naming guidelines for creating model instances from raw data
> Java: Guidelines for azure-identity dependency, quantum group

- docs/typescript/design.md
We don't really use the `details` convention but it's in the general guidelines so presumably at one point we all agreed to it? Regardless I made it optional. Otherwise these are just TS-specific tweaks.
> Implement model types guidelines

- releases/2020-11/dotnet.md
FYI @TimothyMothra I've updated this link that was broken by your PR https://github.com/Azure/azure-sdk-for-net/pull/18494 to use a release tag instead of master.
> Fix opentelemetry link

- css/customstyles.css
Code Preview with no wrap
Half part of https://github.com/Azure/azure-sdk/issues/2157
Makes code preview to use scroll horizontal instead of wrapping down the code
> No wrap on preview code

- releases/2020-11/dotnet.md
fix: #2404
Replacing the link from master to a previous release so it is still valid
> update link with previous release tag

- docs/policies/releases.md
@salameer you added these TBD sections with https://github.com/Azure/azure-sdk/pull/2093. I'm removing them because they ended up hijacking the anchor tags (https://azure.github.io/azure-sdk/policies_releases.html#net) from the package versioning section for each language. If we want to add instructions back here at some point I suggest we add them in the package versioning section for each language.
> Remove TBD sections

- _data/tables/net_standard_verbs.yaml
- _includes/tables/standard_verbs_row.html
- _includes/tables/standard_verbs_template.html
- css/customstyles.css
- docs/dotnet/introduction.md
fixes: #2435
Current table:
https://azure.github.io/azure-sdk/dotnet_introduction.html#general-client-standardize-verbs
Updated table: (Demo for how it would look)
https://vhvb1989.github.io/azure-sdk/dotnet_introduction.html#general-client-standardize-verbs
Main table:
https://azure.github.io/azure-sdk/general_design.html#general-client-standardize-verbs
.NET is currently using a different table format and info than any other language.
This PR updates the table design to follow the genal design and all other langs tables.  @annelo-msft @KrzysztofCwalina  please let me know if .NET needs to have a different layout for this table (as the current layout is) and I can update the style only without changing the layout:
.NET layout:
General layout (general and non NET langs)
> Update NET verbs table to be like all other langs and intro

- docs/dotnet/introduction.md
Our long running operations are hard/impossible to mock add guidelines to allow mocking them.
Also add some learnings from mistakes we made with storage SDK around extension methods and mock-ability.
> More mocking guidelines

- docs/policies/releasenotes.md
- eng/pipelines/generate-releasenotes.yml
- eng/scripts/Generate-ReleaseNotes.ps1
- eng/scripts/release-template/java.md
- Initialize GroupId property before expanding pattern string to allow groupId value to show up in Java.
- Update documentation for producing release notes and link to it in the Create/Update release notes oullrequest.
> Update generate release notes

- eng/scripts/Generate-ReleaseNotes.ps1
Bug fix to get `Generate-Release-Structure.ps1` running as part of Generate-ReleaseNotes.ps1
> Fix bug in Generate-ReleaseNotes.ps1

- _data/releases/latest/dotnet-packages.csv
The github links are case-sensitive so the path has Iot but the package is IoT so at least for now we are working around by providing a custom link template.
> Fix case-sensitive link for device update

- .github/CODEOWNERS
This will split up the code owners/reviewers up by language and avoid adding everyone to all release notes for different languages.
> Split codeowners up by language

- docs/policies/README-TEMPLATE.md
Locale guideline has both the correct and incorrect links identical. Adding "en-us" for a bad example.
> Correcting locale guideline

- releases/2021-04/cpp.md
nit follow up from https://github.com/Azure/azure-sdk/pull/2702#discussion_r610938665
> Remove extra new line in release changelog from cpp for April Release

- docs/dotnet/introduction.md
This unifies rules between clients and LROs in terms of mockable properties.
> Add client properties to mocking guidelines

- releases/2020-10/ios.md
- releases/2020-11/ios.md
- releases/2021-01/ios.md
- releases/2021-02/ios.md
- releases/2021-03/ios.md
FYI @tjprescott your recent changes broke these links so I changed them to use the release tags.
> Use tags for ios changelog links

- eng/scripts/Generate-Release-Structure.ps1
- eng/scripts/Generate-ReleaseNotes.ps1
- Exclude "dotnet.md", "java.md", "js.md", "python.md" when copying over release template for other languages.
- Only copy over the template when there is generated yml data.
> Condition the creation of the release markdown files

- docs/general/terminology.md
Just a little typo I found while reading the docs.
> Fixed a typo in terminology.md

- docs/policies/support.md
This PR updates the support policy for JS around runtimes.
- Link to official docs on LTS versions of Node.js rather than the test matrix we maintain
~~- Include note on browsers with text copied from https://azure.github.io/azure-sdk/typescript_design.html#ts-platform-support~~
Other changes:
- My formatter formatted the file, so a whole bunch of whitespace only changes
- Fix the link texts to not be just the word "here" which is bad for accessibility
@xirzec I wanted to instead just add link to https://azure.github.io/azure-sdk/typescript_design.html#ts-platform-support, but would hold that off until other languages have a similar section.
_Tip to reviewers: Use the "Hide whitespace changes" option to reduce the noise in the PR diff_
> Update support policy with details for JS runtimes

- _data/tables/clang_standard_verbs.yaml
- docs/clang/design.md
fixes: https://github.com/Azure/azure-sdk/issues/2434
Current table view:
https://azure.github.io/azure-sdk/clang_design.html#clang-apisurface-standardized-verbs
Demo of after the change:
https://vhvb1989.github.io/azure-sdk/clang_design.html#clang-apisurface-standardized-verbs
> enhance clang standard verbs table

- docs/java/implementation.md
- docs/java/introduction.md
- docs/java/spring.md
A small batch of guidelines updates:
* When to use Client suffix for sub-clients
* Immutability expectations around model collection types
* PollerFlux / SyncPoller terminal state expectations (no voids)
* Stronger guidance around enums
* Fix guideline around management plane group expectations
* Remove todo around LRO rehydration
> Java guidelines updates for May

- docs/policies/support.md
- Bring more attention to the fact that we do not support dependencies that reach EOL
- Add note that dropping support for EOL dependencies will be done without increasing major version
> Note that dropping support for EOL dependencies will be done without increasing major version

- docs/policies/support.md
This PR refines the message on Azure SDK dependencies not being supported after end of life based on discussions with CELA and Azure Global
> Refine Azure SDK dependency support

- _data/releases/latest/ios-packages.csv
- _includes/releases/variables/ios.md
- eng/pipelines/template/steps/generate-releasenotes.yml
- eng/pipelines/version-updater.yml
- eng/scripts/Generate-ReleaseNotes.ps1
- eng/scripts/PackageList-Helpers.ps1
- eng/scripts/PackageVersion-Helpers.ps1
- eng/scripts/Update-DevOps-WorkItems.ps1
- eng/scripts/Update-Release-Versions.ps1
- Update release tag retrieve to be based on graphql instead of rest
that allows us to retrieve just specific tags by date and also
retreive the dates of tags in the same query
- Use release tags for determining what released for a given release period
- Use an isolated clone for upating the notes from the scripts we run
so that the updated scripts can be used while maintaining the yml data seperate
- Clean-up the pipelines to share common variables
> Update release note generation

- docs/policies/releasenotes.md
- docs/policies/releases.md
Update the change log headings based on feedback.
> Update change log common headings

- eng/scripts/Generate-ReleaseNotes.ps1
- eng/scripts/PackageList-Helpers.ps1
Extend tha generate release notes automation to accomodate all track 2 packages regardless of the groupId.
> Extend automation to include all java track 2 packages

- releases/2021-01/java.md
azure-spring-cloud-telemetry package was deprecated and [deleted from the azure-sdk-for-java repo](https://github.com/Azure/azure-sdk-for-java/pull/22200). This PR removes the link to its changelog referenced in this repository.
> Remove link to deprecated spring cloud telemetry changelog

- docs/java/spring.md
our official name is changed to *Spring Cloud for Azure* , to avoid confusion with Azure spring Cloud, so changing the guideline as well
> correct official name of spring libraries

- docs/golang/implementation.md
> Fix typo in golang/implementation.md

- docs/java/introduction.md
`circumstnaces` to `circumstances` in introduction.md
> Fix typo in java/introduction.md

- docs/dotnet/introduction.md
I noticed the Synapse team was missing a public constructor on their [`SparkBatchOperation` type](https://apiview.dev/Assemblies/Review/0ee110d9d296455a9fb663b95f1f8c2a#Azure.Analytics.Synapse.Spark.SparkBatchOperation).
I checked the guidelines so I could refer to it, and the guidance is in the text, but it's not called out in a specific guideline.  I'm hoping to add that for clarity.
This is the guidance in the [guidelines text](https://github.com/Azure/azure-sdk/pull/3359/files#diff-d1668aaa12d853c4d2a8d1bf803705a97fcbf6d557f2be15d17623030a556b7dR582):
> Client libraries need to inherit from Operation<T> not only to implement all abstract members, but also to provide a constructor required to access an existing LRO (an LRO initiated by a different process).
> Add public constructor guideline for LRO

- README.md
- eng/README.md
fix "Javascript" to "JavaScript" in README.md.
fix "recomendation" to "recommendation" in eng/README.md
> Fix typos in README.md

- docs/general/azurecore.md
Limit distributed tracing headers to W3C Trace-Context. This is important to keep this set closed, especially for CORS configuration in Azure.
> Remove etc from distributed tracing header list

- docs/dotnet/refs.md
The old link pointed to an archived repo so needed to update to official docs site.
> Update .NET Standard 2.0 link

- docs/dotnet/introduction.md
None of our libraries uses Client**s**Options for its `ClientOptions` type.  Also, it wouldn't work well in the case that a client was added to a library after it GA'ed.
> Update .NET ClientOptions guidelines to reflect precedent

- docs/general/azurecore.md
As found in https://github.com/Azure/azure-sdk-for-js/issues/13391, we don't really support the CIDR notation for NO_PROXY. Removing it from the guidelines.
> Remove the guideline around CIDR notation

- _data/releases/2021-05/java.yml
@FabianMeiswinkel @kushagraThapar this looks to have been broken by https://github.com/Azure/azure-sdk-for-java/pull/26527. I updated it based on those changes but is there a more stable link we can use here so that it doesn't break again in the future? Do you guys have any release tags we can use to keep this stable?
> Fix broken spark link

- _includes/releases/nav.md
- releases/retired/index.md
Add the standard language navigation bar to the retired releases page. Without it, you could be scrolling for days.
@mario-guerra As of right now, there are no retired packages to list for non-Tier 1 languages. Do you want those non-Tier 1 languages removed from this navigation bar?
> Add language navigation to retired releases page

- _data/releases/latest/python-packages.csv
The package was deprecated today. Update CSV with replacement package name and migration guide.
> Mark Python azure-applicationinsights package as deprecated

- _includes/releases/header.md
Use HTML tags to correct the unordered list formatting. Also, remove the "en-us" locale string from the link.
After changes:
> Fix unordered list formatting on retired releases page

- docs/python/documentation.md
Adds guidance for documenting default values in docstrings.
> [Python] add docstring default guidance

- docs/policies/releases.md
npm tags are no longer required tobe set manually and this is automatically set based on version being published and versions present on npm.
> Updated release policies to mention about JS npm tags

- _includes/releases/header.md
- releases/latest/all/dotnet.md
- releases/latest/all/java.md
- releases/latest/all/js.md
- releases/latest/all/python.md
Adding clarity based on feedback from an internal partner team.
> Clarify verbiage in header of Azure SDK releases page

- _data/releases/latest/java-packages.csv
Fixed the package has no type on it. 
The issue will cause the package toc has no children for APIs to categorized.
> Add type for AgriFood pacakge

- docs/android/design.md
- docs/ios/design.md
Based on recent APIView feedback for AzureCommunicationChat. Our existing guidance was inconsistent with other languages. This adds clarity regarding which API versions should be included in stable and beta releases and to which API version "latest" should apply to.
cc/ @johanste
> [Mobile] Update API version guidelines for iOS/Android

- docs/dotnet/implementation.md
- docs/dotnet/introduction.md
.NET style only allows `var` for obvious types, like instantiation. .NET SDK guidelines should match this guidance to avoid confusion.
> Use `var` for .NET docs where acceptable

- .github/CODEOWNERS
Onboarding to the role as release driver and updating the codeowners file as required.
> Update .NET Release Driver

- _data/releases/latest/python-packages.csv
Resolves Azure/azure-sdk-for-python#24775
@danieljurek @sima-zhu can you double check this?
The "core" page: https://azure.github.io/azure-sdk-for-python/core.html
Doesn't have `core` showing up on it. This is because we've recategorized `core` service under `Other` category.
To keep it consistent, let's move `azure-common` to `Other`. Can you double check the space I updated? I'm pretty it should get used as we expect.
> Recategorize azure-common to exist under the 'Other' label on github.io

- docs/general/azurecore.md
The Managed Service Identities product name has been simplified to "Managed Identities".
> Update MSI product name used in guidelines

- _data/releases/2021-11/python.yml
This PR simply deletes a partial duplicate entry for azure-mgmt-monitor that my scripts tripped over in the 2022-11 python releases yaml.
> Remove partial duplicate entry for azure-mgmt-monitor

- _includes/releases/links.md
Change 'Deprecated on {date}' to 'End of life on {date}' to better reflect the state of the library while in transition between date of deprecation and end of life date.
> Change 'Deprecated on' to 'End of life on'

- _data/releases/latest/java-packages.csv
spring-cloud-azure-resourcemanager is currently a `mgmt` package. It should be a `spring` package. We [skip](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/scripts/Language-Settings.ps1#L467) onboarding spring packages to docs and this package should not be in our docs.
> Classify spring-cloud-azure-resourcemanager as a spring package instead of mgmt

- docs/ios/design.md
https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes
Apple has flip-flopped and now has deprecated bitcode. Thus, we need to switch our guideline from requiring it to _not_ requiring it.
> Update bitcode guideline

- _data/releases/latest/java-packages.csv
We recently submitted a fix which we can read the version from csv for azure packages outside of our mono repo. The change has checked in, so we read the 1.0.0 version in csv instead of the latest 1.0.1. I have the PR to update the version
> Update the durable task version

- docs/java/introduction.md
There is a typo in the java.time package recommendation.
> Fix java guidelines typo

- _data/releases/latest/cpp-packages.csv
We decided against having a KeyVault Common package in C++ and instead went with a source file sharing approach. We don't need this artifact visible anymore, especially since I don't think it is adding any value.
@weshaggard please correct me if I am mistaken and if we need to keep this entry for some reason. If we **really** need to keep it, we should at least mark is at deprecated.
It was removed from the vcpkg package registry before GA:
https://github.com/microsoft/vcpkg/pull/22491
And from the source:
https://github.com/Azure/azure-sdk-for-cpp/pull/2905
The last update to the package index was here, for `beta.3`:
https://github.com/Azure/azure-sdk/pull/2970
Here are the current documented/visible C++ releases for reference:
https://azure.github.io/azure-sdk/releases/latest/#c
> Remove Azure Security KeyVault Common package from the C++ index since it never GA'd

- docs/general/design.md
- docs/general/terminology.md
Add guidance on number of service clients and situations to consider multiple service clients.
Also added guideline to support api version parameter on client constructors.
Fixes #4486
> Client guidelines

- docs/tracing/distributed-tracing-conventions.md
- docs/tracing/distributed-tracing-conventions.yml
This change aligns Azure SDK with OpenTelemetry semantic conventions [v1.17.0](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.17.0):
- unifies attribute names for messaging
- requires Azure SDKs to populate OTel schema versions
- recommends adding library name and version to tracer.
With this, we'll have 3 azure-specific attributes (with the opportunity to add more in the future if needed):
- `az.namespace` for RP namespace
- `az.client_request_id` for `x-ms-client-request-id
- `az.service_request_id` for `x-ms-request-id`
And will reuse available attributes defined in otel.
> Converge Azure SDK with OpenTelemetry semantic conventions

- _data/releases/latest/dotnet-packages.csv
This package was renamed to Azure.Monitor.OpenTelemetry.Exporter in https://github.com/Azure/azure-sdk/pull/2359
> Deprecate Microsoft.OpenTelemetry.Exporter.AzureMonitor package

- _data/releases/latest/dotnet-packages.csv
**Summary of changes**
- Update support end dates for `Microsoft.WindowsAzure.Caching` and `Microsoft.WindowsAzure.Caching.MemcacheShim`, per a conversation with @lfraleigh
- Deprecate `Microsoft.Azure.ConfigurationManager` and `Microsoft.WindowsAzure.ConfigurationManager`
> Update support end dates and deprecate NuGet packages

- _data/releases/latest/js-packages.csv
- _data/releases/latest/python-packages.csv
**Summary of changes**
- Mark the Track 1 `azure-monitor` Python package as deprecated and update its name to "Resource Management - Monitor"
- Update the Track 1 `azure-monitoring` JS library's name to "Resource Management - Monitor"
> Updates to JS & Python Monitor resource mgmt packages

- docs/dotnet/introduction.md
Also adds an aka mention of another common form including "Newtonsoft".
> Fix intended link in .NET guidelines

- eng/scripts/Query-Azure-Packages.ps1
Needs to go in with https://github.com/Azure/azure-sdk-for-go/pull/19971
> Update golang package regex to detect arbitrary length directory trees

- eng/ci.yml
- eng/pipelines/generate-release-structure.yml
- eng/pipelines/version-updater.yml
All Windows and Linux pipelines should use 1ES pools by default, unless they need to run in the DevOps Pool for a specific reason.
> Use 1ES pools

- eng/scripts/Update-Release-Versions.ps1
When deprecating a package, if a replacement package exists, check if the replacement name matches the deprecated name.
Skip the migration guide check if the names are the same.
> Check if replacement name matches deprecated name

- eng/scripts/Query-Azure-Packages.ps1
Change to support https://github.com/Azure/azure-sdk-for-go/pull/18841, see [discussion](https://github.com/Azure/azure-sdk-for-go/pull/18841#issuecomment-1451179175).
Paired with https://github.com/Azure/azure-sdk-for-go/pull/20344
> Support profile directory as top level directory for package properties

- eng/scripts/Generate-Package-Index.ps1
We want this to add a package list section to https://learn.microsoft.com/en-us/azure/developer/go/ for better SEO to the microsoft site.
> Add go generate package index supported languages

- docs/general/implementation.md
This relates to the text on "using 3rd party technologies" that Jeffrey Richter and I created & reviewed offline with the architectural board.  I've merged that text into the Dependencies section.  I also fixed a few markdown errors that I found elsewhere in this file while I was in there.
If further work is needed on the 3rd party tech piece, reviewers are asked to provide replacement text as required -- thank you!
> Added statement on 3rd party tech usage

- js/customscripts.js
If the search query parameter was not lowercase then it wouldn't find any thing in the search. This makes sure the filter is always lowercase.
> Fix package index query parameter

- _data/releases/latest/java-packages.csv
Our java sdk docs have not been updated since end of last year.
unlike all our C# and Python packages, the docs pipeline does not seem to be automatically detecting and updating the package version in this file.  I'm manually updating it to see if that unblocks our docs, and gets them updated to the out latest public release.
> manually update the package version for speech Client-SDK package.

- _data/releases/2023-05/cpp.yml
Core 1.8.2, then core 1.9.0, then 1.10.0-beta.1, then identity, then all keyvault alphabetically, then all storage alphabetically.
> Rearrange C++ release notes order to tell a consecutive story

- _data/releases/latest/python-packages.csv
Plug and Play is no longer a requirement, so removing from the IoT Device SDK TOC.
> update python csv to remove plug and play from TOC

- _data/releases/latest/dotnet-packages.csv
@weshaggard 
The preview version of Azure.ResourceManager.Hci was being set to 2.0.0-beta.1. This version was unlisted on nuget but the automation that updates the versions was still finding 2.0.0-beta.1 because the release and tag for Azure.ResourceManager.Hci_2.0.0-beta.1 both still existed. I've removed the release and tag and, as per our conversation, the preview version is getting set to empty since the GA version is higher.
> Remove the preview version of Azure.ResourceManager.Hci

- docs/dotnet/implementation.md
- docs/dotnet/introduction.md
This PR updates the implementation docs to be in line with our current patterns for RequestFailedException usage.
> Update RequestFailedException docs

- _includes/releases/notes/package_display_names.md
Moved the counts to be on the same line as the header except for the total at the bottom.
> Move package counts at the end of the section headers

- eng/scripts/release-template/c.md
- releases/2023-06/c.md
Follow-up from https://github.com/Azure/azure-sdk/pull/6143#issuecomment-1558119606
> Update c.md template to default to no release and update latest embedded c release notes for June 2023 (no release)

- eng/scripts/Generate-Package-Index.ps1
Resolves https://github.com/Azure/azure-sdk/issues/5998
This removes packages with empty `ServiceName` values from [go-packages.csv](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/go-packages.csv) and [go-all.md](https://github.com/MicrosoftDocs/azure-dev-docs-pr/blob/bdd3d924361d91932fc444f172514d84b4be56bd/articles/includes/go-all.md?plain=1#L249) because they are deprecated/track 1.
> Skip deprecated go track 1 packages in release doc generation

- eng/scripts/Update-Azure-Package-Data.ps1
Backing data for https://aka.ms/azsdk/release-dashboard
The script needs a bit of cleanup and a daily/weekly pipeline, but I wanted to get the initial approach up for review. Subsequent work will include sourcing this data out of the azure-sdk repository yaml files to get a more exact view of what packages azure sdk owns, and to provide an alternative to querying all the package feeds every time.
> Add script to query all package version data and update kusto database

- _data/releases/latest/python-packages.csv
Deprecating the Python `azure-schemaregistry-avroserializer` package.
PR with doc/package updates in Python repo: https://github.com/Azure/azure-sdk-for-python/pull/31667
> Update CSV files for azure-schemaregistry-avroserializer deprecation

- _data/releases/latest/dotnet-packages.csv
Retire Azure.Communication.Calling and replace it with Azure.Communication.Calling.WindowsClient.
Azure.Communication.Calling was the old beta SDK that never made to GA. Since we had released GA under Azure.Communication.Calling.WindowsClient, it's time for us to retire the old SDK.
There isn't much usage of the Azure.Communication.Calling, so we leave the migration guide as optional.
> Retire Azure.Communication.Calling .net SDK package

- .github/CODEOWNERS
There were two main types of changes:
1. The path entries should have had a leading slash as these paths are all in the root of the repository.
2. The single file entries are being changed to use their glob equivalent.
Both of these changes will allow the CodeownersParser and the CodeownersLinter to better process them as both tools use Microsoft.Extensions.FileSystemGlobbing. The azure-sdk-for-language repositories were all similarly updated earlier this year.
> Fix CODEOWNERS entries for correctness and so the parser and linter can recognize them

- _includes/releases/variables/dotnet.md
- _includes/releases/variables/java.md
- _includes/releases/variables/js.md
- _includes/releases/variables/python.md
- eng/scripts/Update-Release-Versions.ps1
- Ensure the link caching is working by making the pre_suffix match the final link that is getting cached (i.e. & -> &amp;)
- Skip always checking ghdoc links if there is a valid msdoc link because we never display the ghdoc link if there is a valid msdoc link.
> Improve link checking perf

- _data/releases/2023-09/go.yml
Manually updating the release notes for Go.
Releases that went out this week are mistakenly being adding to the October release notes, so this PR adds the releases to the September release notes.
> update go sept release notes

- eng/scripts/release-template/go.md
Updating the Go release template to remove a repeated line for future release notes.
@antkmsft pointed this out [here](https://github.com/Azure/azure-sdk-blog/pull/437#discussion_r1325261682)
> Update Go Release Template

- _data/releases/latest/go-packages.csv
This package has been retracted, so the links are now "broken." Hiding listing from docs.
> Hide retracted go entry

- releases/2021-08/go.md
- releases/2021-10/go.md
- releases/2021-11/go.md
- releases/2021-12/go.md
- releases/2022-01/go.md
- releases/2022-02/go.md
- releases/2022-03/go.md
- releases/2022-04/go.md
- releases/2022-05/go.md
- releases/2022-06/go.md
- releases/2022-07/go.md
- releases/2022-08/go.md
- releases/2022-09/go.md
- releases/2022-10/go.md
- releases/2022-11/go.md
- releases/2022-12/go.md
- releases/2023-01/go.md
- releases/2023-02/go.md
- releases/2023-03/go.md
- releases/2023-04/go.md
- releases/2023-05/go.md
- releases/2023-06/go.md
- releases/2023-07/go.md
- releases/2023-08/go.md
- releases/2023-09/go.md
Updating old Go release notes to remove extra line.
@weshaggard suggested this fix [here](https://github.com/Azure/azure-sdk/pull/6655#issuecomment-1734620461).
Related to [this issue](https://github.com/Azure/azure-sdk-pr/issues/1523).
> Cleanup Go release notes

- eng/scripts/Query-Azure-Packages.ps1
Maven search service still has a lot of reliability issues so I'm going to add back logic to handle those errors.
> Revert "Remove error handling around maven so we know if it fails"

- _data/releases/latest/dotnet-packages.csv
Adding Microsoft.FeatureManagement to the CSV file which needs to be there for docs. It looks like they were half onboarded, having json files in the azure-docs-sdk-dotnet, but were never added to the CSV file.
> Add Microsoft.FeatureManagement to the CSV file

- _data/releases/latest/dotnet-packages.csv
When re-adding the entry back, it was close but slightly off, the service name was set to other and should have been app configuration.
> fix FeatureManagement's CSV entry so the service level overview is generated properly

- .github/CODEOWNERS_baseline_errors.txt
- eng/common/pipelines/codeowners-linter.yml
This change includes the CODEOWNERS baseline error file as well as the pipeline yml file.
CODEOWNERS is now going to be linted. _This PR contains the existing linter errors, deduped, which are used to filter results, otherwise this pipeline couldn't be run on PRs that contain CODEOWNERS changes without the several hundred issues being fixed, which is not ideal._ The linter will run daily and on every change to CODEOWNERS or the baseline file. Specific details of the linting can be found [here](https://github.com/Azure/azure-sdk-tools/tree/main/tools/codeowners-utils#linting) but here is what's being verified in a nutshell.
- Metadata tags - PRLabels, ServiceLabels, ServiceOwners (previously /&lt;NotInRepo&gt;/, both are still valid for the moment) and AzureSdkOwners (new, used for issue …
> Add CODEOWNERS linter baseline file and linter pipeline yml file.

- eng/common/pipelines/templates/steps/sparse-checkout.yml
The codeowners-linter pipeline needs the sparse-checkout template. For other azure-sdk-for-lang repositories this is pushed out when eng/common changes but this does not happen for azure-sdk.
> Add sparse-checkout template, needed by the codeowners-linter pipeline

- docs/typescript/design.md
Per extended discussion with JS architects, we have decided to align to DefinitelyTyped's support window.
> [ts] Update TypeScript min version guidelines

- docs/tables/registered_namespaces.md
Adding the azure.developer.* namespace for services like Dev Center and Load Testing.
> Add azure.developer.* namespace to registered namespaces

- docs/dotnet/introduction.md
The "full sample" link redirected to a message asking customers to read the official doc on Learn:
This change eliminates that extra click.
> Update mocking guidelines section for .NET

- _data/sidebars/releases_sidebar.yml
- _includes/releases/specs.md
- releases/latest/all/preview-only-specs.md
In order to see a list of all the specs that don't have a GA version yet there was a request to get a list of all the specs that only have preview versions. This new tab adds that view.
> Add Preview Only tab to the spec index page

- _data/releases/latest/python-packages.csv
The package `azure-ai-vision` was a beta package (less than a year old) with Image Analysis APIs, with plans to add more API surfaces to it to support other vision scenarios. However, plans have changed and that did not happen. We now have a separate SDK (package) dedicated to Image Analysis, package name `azure-ai-vision-imageanalysis`. Deprecating the old in favor of the new.
> Deprecate Python package `azure-ai-vision`

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- Gemfile
- Gemfile.lock
- _config.yml
A number of problems, including a Gemfile.lock that had outdated and incompatible versions with Ruby 3, which github-pages now requires. Basically copied most of my personal site's devcontainer configuration which works.
Unfortunately, we cannot have VSCode prompt to open the browser to the site automatically. After about 15 minutes, it seems impossible to have it direct to a subdirectory of the local server address and port.
> Fix devcontainer for azure-sdk site

- eng/ci.yml
- eng/pipelines/generate-release-structure.yml
- eng/pipelines/template/steps/generate-releasenotes.yml
- eng/pipelines/version-updater.yml
We already sync eng/common periodically so we should reference things directly from the eng/common in the repo isntead of taking repo refs to azure-sdk-tools for some things and not other things. This has causes some issues troubleshooting and some inconsistencies so we should stop doing it.
> Remove azure-sdk-tools ref and sync eng/common instead

- eng/pipelines/version-updater.yml
Follow-up after https://github.com/Azure/azure-sdk/pull/7201 because the clones were going into the wrong directory.
> Fix paths in version update pipeline

- _data/releases/latest/python-packages.csv
This creates an entry in the "python-packages.csv" file for `corehttp`, the generic, non-Azure branded version of `azure-core`.
An ADO work item (20925) was recently made for the Python `corehttp` package, however, it was created after the release actually happened, so I am uncertain if the bot will automatically populate this entry. 
Note, I did not update "inventory.csv" because I don't see azure-core or any of the other python core libraries listed there.
FYI @scbedd
> Add corehttp python package

- docs/python/implementation.md
azure-devtools was removed with https://github.com/Azure/azure-sdk-for-python/pull/34841 so removing this link. 
@mccoyp @scbedd let me know if there is an alternative we should reference.
> Fix broken link for deleted azure-devtools

- _data/releases/latest/dotnet-packages.csv
- _data/releases/latest/java-packages.csv
- _data/releases/latest/js-packages.csv
- _data/releases/latest/python-packages.csv
Deprecate Communication Network Traversal package from all supported languages: java, python, .NET, Javascript
> Deprecate Communication Network Traversal package from supported languages

- .devcontainer/Dockerfile
- Gemfile
- Gemfile.lock
Fixes break in devcontainer with explicit version dependency on
nokogiri, which otherwise will pull a newer version that doesn't support
Ruby 2.7.
> Upgrade github-pages dependencies

- _data/releases/latest/python-packages.csv
Fixing Display name of Communication Python SDK, Currently it is like below:
Communication Messages
Overview
azure.communication.messages.
> Fixing Communication message display name for Python SDK

- _data/releases/latest/dotnet-packages.csv
The OTel Live Metrics package has already been marked as deprecated on nuget.org. The package never made it out of Beta, so marking end of support date as today. Its functionality moved to a separate package.
> Deprecate OTel Live Metrics NuGet package

- _data/releases/latest/dotnet-packages.csv
Prevent display of this row on the Learn docs page:
> Hide deprecated brokered authN NuGet package from docs

- eng/pipelines/template/steps/generate-releasenotes.yml
Adding clause for the second Friday of the month of July to be pushed out 1 week.
> updating release notes generator with exception for july

- docs/cpp/implementation.md
- docs/cpp/introduction.md
1. 	Source code layout.
1.	Banning defining non-Azure SDK types in SDK headers.
1.	All types and methods must be in a namespace.
1.	Discussion on Cancellation and how it works.
1.	Clarification on how to use the C++ “enum” type, and additional information on how to use ExtendableEnumerations.
1.	Reference to the C++ core guidelines.
1.	Note that this section is missing the *exceptions* to the core guidelines – I know we have them, but I’m not 100% sure what they are, to be honest.
1.	C++ Struct types should have no methods. If the struct has methods, it’s a class (local convention)
1.	Updated to include a ban on using connection strings in services introduced after 1/1/2024
1.	I’m looking for general guidance on how we handle Spring Grove related changes to API Guidelines.
1.	Added a …
> Updates to C++ API Guidelines, covering Context and other changes.

- .github/CODEOWNERS
- docs/identity/README.md
Azure Identity SDKs are used in almost every scenario and will continue to be heavily used as usage of Entra ID expands throughout 1p and 3p customers.
Over the years some knowledge has accumulated and as a team we would like to document these decisions as well as backfill
previous decisions, designs, and other docs needed by new team members.
We wanted a place that is:
- Public by default
- Language agnostic
- Supports Markdown
- Is easy to add changes and review changes
This is an experiment, and we should evaluate whether we're getting the value we need out of it (and whether there's enough
engagement) but as a starting point we plan to bootstrap this in a Q&A.
> [identity] Bootstrap Identity docs section

- docs/rust/implementation.md
- docs/rust/introduction.md
Also fixes a code fence issue that manifested in tree-sitter grammars.
> Fix links in Rust's Implementation guide

- _data/releases/latest/python-packages.csv
Updating `azure-ai-evaluation` metadata to slot under Cognitive Services in the MS Learn ToC. `DisplayName` of "AI Evaluation".
> update ai-evaluation metadata

- _data/releases/2021-08/cpp.yml
- _data/releases/2021-09/cpp.yml
- _data/releases/2021-10/cpp.yml
- _data/releases/2021-11/cpp.yml
- _data/releases/2022-01/cpp.yml
- _data/releases/2023-04/cpp.yml
- _data/releases/2023-05/cpp.yml
- _data/releases/2024-03/cpp.yml
- _data/releases/2024-04/cpp.yml
Bringing in changes from https://github.com/Azure/azure-sdk-for-cpp/pull/6048
Note that the changes to "Other Changes" section is not included, because over here that section is removed entirely.
> Fix/unify liks in C++ release notes

- docs/rust/implementation.md
- docs/rust/introduction.md
We are reevaluating options. The existing approach required importing a trait when most consumers probably wouldn't understand why or even need it for its intended purpose.
> Removing mocking guidelines for Rust

- docs/tracing/distributed-tracing-conventions.md
- docs/tracing/distributed-tracing-conventions.yml
The official name is "Key Vault". We should use the correct name in official documentation.
> Fix "Key Vault" product name

- docs/dotnet/introduction.md
If an Azure service provides a REST API to cancel a long-running operation, .NET Azure client libraries put the `Cancel` method on a public subtype of `Operation`.  This is not clearly represented in the C# guidelines -- this PR updates the guidelines to reflect the guidance more clearly.
> Clarify guidelines for LRO subtypes

- docs/rust/introduction.md
This was agreed to in a 2024-10-29 meeting of stakeholders and partners. It simplifies the API, reduces compile times and compiled code bloat because of monomorphization, and lends itself to automatic tracing if we so choose to rely on it.
We can also always change parameters to generic types without incurring a breaking change later if we hear significant feedback.
> Declare concrete parameter types for Rust

- docs/rust/implementation.md
- docs/rust/introduction.md
This was agreed to in a 2024-10-29 meeting of stakeholders and partners. It simplifies the API and we can always add builders later without being a breaking change.
> Use PODs instead of builders for Rust options

- docs/rust/implementation.md
- docs/rust/introduction.md
- docs/rust/refs.md
SafeDebug still needs to be added, but that shouldn't take long if these guidelines seem appropriate.
> Recommend SafeDebug over Debug for Rust

- _data/releases/latest/dotnet-packages.csv
The Azure.AI.Projects entry was updated in this [PR](https://github.com/Azure/azure-sdk/pull/8293) yesterday but the Type column was left empty which is why this is showing up under Uncategorized instead of under Cognitive Services.
> Update Azure.AI.Projects entry to set Type column to client

- docs/dotnet/introduction.md
- docs/dotnet/refs.md
The focus of these changes is to update information around the strategy for managing .NET target frameworks for Azure SDK packages and versions for .NET runtime dependencies.  Also included are some light refactoring of structure for improved organization and some typo fixes for better readability.
> [.NET Guidelines] Target frameworks + dependencies

- eng/scripts/release-template/index.md
- releases/2025-03/index.md
Add Rust release notes to the release template and March 2025 release index
> Add Rust release notes to the release template and March 2025 release index

- eng/scripts/Query-Azure-Packages.ps1
Now that we are updating package info as part of the pipeline that should give us the correct repo path so we shouldn't need to guess based on the name.
> Remove repopath guess for new packages

- docs/typescript/implementation.md
> [TypeScript] Deconflict duplicate guidelines ids

- docs/clang/design.md
- docs/clang/implementation.md
- clang-design-naming-funcstatic
> [C] Deconflict duplicate guideline ids

- docs/cpp/implementation.md
- docs/cpp/introduction.md
The following IDs are used in more than one guideline. The means that links to the guidelines are ambiguous, and as we are indexing guidelines into Azure AI Search, we require the guideline IDs to be unique.
- cpp-lro-return
- cpp-design-client-sync-api
- cpp-design-naming-variables-public-global
- cpp-design-private-types-private
- cpp-service-client-constructor-minimal
- cpp-version-change-on-release
> [C++] Deconflict duplicate guideline ids

- docs/android/design.md
- android-models-fluent
- android-versioning-no-previews-in-stable
> [Android] Deconflict duplicate guideline IDs

- docs/dotnet/implementation.md
- docs/dotnet/introduction.md
The following IDs are used in more than one guideline. The means that links to the guidelines are ambiguous, and as we are indexing guidelines into Azure AI Search, we require the guideline IDs to be unique.
- dotnet-parameter-lro-qualifier-required
- dotnet-build-net-standard
- dotnet-lro-waituntil
- dotnet-params-complex
- dotnet-problems-too-many-types
- dotnet-service-client-entry-point
- dotnet-version-change-on-release
> [.NET] Deconflict duplicate guideline ids

- docs/java/introduction.md
- java-maven-url
- java-models-fluent
- java-versioning-highest-api
- java-versioning-select-api-version
This PR ensures the IDs are not duplicated where the content of the guideline is different, either by choosing deconflicting id names, or, in one case, by ensuring the guideline is copied in its entirety.
> [Java] Deconflict duplicate guideline ids

- docs/ios/design.md
- docs/ios/implementation.md
The following IDs are used in more than one guideline. The means that links to the guidelines are ambiguous, and as we are indexing guidelines into Azure AI Search, we require the guideline IDs to be unique.
- ios-versioning-no-previews-in-stable
- ios-attr-available
> [iOS] Deconflict duplicate guideline ids

- docs/general/design.md
- general-repeatable-requests-support
> [General] Deconflict duplicate guideline ids

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/pipelines/templates/steps/git-push-changes.yml
- eng/pipelines/template/steps/generate-releasenotes.yml
- eng/pipelines/version-updater.yml
These changes were used to test switching to fine-grained github pats over using the classic pat.
We have discovered a few issues with creating pull requests across orgs, in particular making a pull request from fork in the azure-sdk bot account into another org like MicrosoftDocs or dotnet does not work. This is because the fine grain tokens are scoped to a single org. This can kind of work for public repos if you don't use a token but this does not work at all for private repos, see https://github.com/orgs/community/discussions/24549.
> Revert testing of fine-grain pats

- eng/scripts/Query-Azure-Packages.ps1
This adds the io.clientcore packages as well as outputs a warning for any packages we find a release tag for but didn't get from our maven query. There appears to be some issues (hopefully temporarily) where the search api doesn't return any packages that only have a single version published.
> Add java io.clientcore groupid

- _data/releases/latest/python-packages.csv
This package now only contains Logs APIs. Renaming it accordingly.
> Update display name for Python Monitor Query package

- _data/releases/latest/js-packages.csv
The package was split as part of the TypeSpec conversion. Marked as deprecated and no longer supported, due to Azure policy violations.
> Deprecate Monitor Query package for JS

- eng/scripts/Update-Spec-Versions.ps1
With all the TypeSpec conversions of older specs we should remove that from the condition. We will only return brownfield if there are no existing stable versions.
> Fix condition in GetServiceLifeCycle function
